### ISSUE TITLE
Duplicate text in "Book" configuration 

### ISSUE THREAD

**Issue by wrigleyDan** [o19s/quepid#1006]
**Describe the bug**
When configuring a book there is an option to check when supporting implicit judgments. The text of this setting is wrong and sort of duplicated.
Instead of saying `Support implicit judgements` it says `Support implicit judgements Supports Implicit Judgements?`
Also, see the added screenshot.

**To Reproduce**
1. Go to 'http://app.quepid.com/'
2. Click on 'Books' in the top level navigation and select any of the books you have (assuming you have at least one book)
3. Click on 'Edit Book'
4. Locate the text `Support implicit judgements Supports Implicit Judgements?`

**Expected behavior**
Change the text to `Support implicit judgements` in order to remove the duplicate.

**Screenshots**
![image](https://github.com/o19s/quepid/assets/54574577/63cd61fa-87cd-40f3-8f26-89ce6b38c00f)

**Additional context**
n/a

**Comment by epugh** [comment]
Thanks...   I think I ran into this whle working on one of the PR thats are open..  I will try and pull that one commit out and tie it to this and clsoe it!  thanks for finding those little bugs that hurt our polish!

**Comment by epugh** [comment]
Fixed!
