### ISSUE TITLE
Migrating to a more modern codebase

### ISSUE THREAD

**Issue by synhershko** [o19s/quepid#101]
Hello there,

We have been using (and supporting) quepid for a while, and I'd like to start a discussion about modernizing the Quepid codebase. Quepid is currently running on RoR as backend (old version, and a pretty much a dead technology now) and Angular 1.something (very very old and EOL).

Would you consider rebuilding the project, piece by piece, using modern technologies? We can help. We propose using React for the frontend, and Typescript/NodeJS or Go for the backend.

Would love to hear your thoughts.

**Comment by epugh** [comment]
Definitely would consider it!   

In fact there is precedent for this: Quepid was originally a server side only Flask app, then moved to Angular 1 + Flask, and then migrated to Rails + Angular 1.  At that point we added in the Teams and various export features to Quepid (plus had a whole suite of "Enterprise" related function when it was a SaaS product).   

Moving to ASL2.0 licensed open source project we did the heavy lift of removing all the Enterprise features, getting Quepid into a Dockerized environment, and paying down a LOT of tech debt.  

Today the things that are holding us back are:
1) Angular 1 ;-).  I get nervous every time I try to update a package on the front end.
2) The design decision that we made to have a single interface used by Raters and Relevance Engineers means that it doesn't quite support either audience as well as we would like.
3) Lack of proper authentication support on the API.   If you want to build your own front end, and hook into the Quepid backend, well, the authentication process is awkward.

I’m really excited about the opportunity to revamp the front end (versus replacing the backend and the database), and I would suggest starting with creating the front end interface for Raters and Relevancy Engineers that we *wish* we had started with!  This could be deployed alongside the existing front end interface till there is enough mass to remove the existing one.   Then, if we see use cases that the existing API is holding us back on, then embark on changing that out.


Eric

**Comment by synhershko** [comment]
Happy to hear that!

I agree starting with the frontend is best. However, some features like authentication will have to wait for a backend rewrite I'm afraid.

Do you have any specs for the revamped frontend interface that you mention?

**Comment by epugh** [comment]
Give me a day to think about this a bit more...   While I've dreamed a bit about what the ideal "relevancy optimization" tool could look like, it has always seemed like a very distant rainbow, or maybe a mirage since the closer you get the further away it looks.   I'll put some thoughts down on paper of what a relevancy optimization UI *could* look like.

**Comment by softwaredoug** [comment]
I take personal responsibility for crufty code during my brief stint as a frontend developer :) Ah the innocent days when Angular 1 was brand new.

Though we should upgrade from Angular 1, I'm not sure I would be for moving away from Angular. Angular as a project continues on and we frequently encounter it with clients. Why not evolve the code base to the latest Angular version? I think that would be less disruptive, with probably a direct migration path, though still a good amount of work. 

From my personal perspective, there's certainly no problem with you writing your own tool that suits your needs. We have good friends that have created several similar tools

- https://github.com/SeaseLtd/rated-ranking-evaluator
- https://github.com/mitre/quaerite

Not to mention tools clients build for their own purposes.

We are fans, users, and contributors of all these things, and they scratch different itches!

**Comment by synhershko** [comment]
@softwaredoug it really is your pick whether to use Angular or React. It is our experience that React is a much better fit for those types of projects but as said it's definitely yours to choose. Regardless, it is going to be a complete rewrite as new Angular shares nothing with old Angular 1.7, you won't be able to share or reuse any piece of the existing code.

**Comment by synhershko** [comment]
Closing for lack of interest, we ended up implementing our own tool which we can evolve with
