### ISSUE TITLE
Query Error: Full Text Does Not Generate Results, Truncated Text Does.

### ISSUE THREAD

**Issue by miguelmesas** [o19s/quepid#1041]
**Describe the bug**
When entering the full text into the query box, no results are generated. However, when a truncated version of the text is used, results are successfully generated. This issue seems to be related to the length of the text input, where longer text inputs fail to produce results while shorter ones work correctly.

**To Reproduce**
Example:
    Full text (no results): "In the heart of a bustling city, a small café hidden among the cobblestone streets offered a peaceful refuge for dreamers. The regular patrons, an eclectic group of artists, writers, and musicians, filled the space with lively conversations and genuine laughter. The walls were adorned with vibrant paintings and inspiring quotes. A young barista, with a talent for creating intricate designs in coffee, served each cup with a warm smile. At dusk, the café transformed into an impromptu stage where local musicians shared their melodies, creating a magical atmosphere that inspired everyone present."

    Truncated text (results): "In the heart of a bustling city, a small café hidden among the cobblestone streets offered a peaceful refuge for dreamers. The regular patrons, an eclectic group of artists, writers, and musicians, filled the space with lively conversations and genuine laughter. The walls were adorned with vibrant paintings and inspiring quotes. A young barista, with a talent for creating intricate designs in coffee, served each cup with a warm smile. At dusk, the café."

**Expected behavior**
It is expected that the application will generate the results.

**Screenshots**
![imagen](https://github.com/o19s/quepid/assets/25994747/3e29b4ce-3901-480c-8525-0cb3d8e51239)

**Additional context**
When executing the query directly in OpenSearch Dashboards with the full text, the search results are generated normally. The text is long because we aim to rank semantic search.

**Comment by epugh** [comment]
@miguelmesas  are you using hosted quepid?  would you believe I just extended the field length yesterday in prod?

**Comment by epugh** [comment]
Here is the PR I just merged...  https://github.com/o19s/quepid/pull/1037.   Need to test why it didn't cover your use case...  your query is only 600 or so characters....

**Comment by epugh** [comment]
Here is my local test: 
![image](https://github.com/o19s/quepid/assets/22395/8272249c-8eef-49d5-9468-c8e679e2d745)

**Comment by miguelmesas** [comment]
Hello @epugh , thanks for responding so quickly. We have the Docker version installed on one of our servers. How could I update it without losing my data?

**Comment by epugh** [comment]
These steps should work for you: https://github.com/o19s/quepid/wiki/Installation-Guide#updating-quepid

Quepid has many frequent releases, so you want to make sure you can upgrade easily!   I will cut a version with the bug fix in the next hour, and post it in #quepid on Relevance Slack...

**Comment by miguelmesas** [comment]
Perfect. Thank you very much for your help.

**Comment by epugh** [comment]
I'm cutting 7.17.1 with the fixes...
