### ISSUE TITLE
Highlight when a query triggers a querqy rule

### ISSUE THREAD

**Issue by clamar-VM** [o19s/quepid#1050]
**Is your feature request related to a problem? Please describe.**
The user may get confused when certain rules are applied to a search, or have no idea that rules they created were used.

Searchandisers want to know when a querqy query is matching a rule or not. They are typically testing whether those rules are working.

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/3b6e1266-cbb6-4d25-b2ff-49e6b7f6f63a)
I would like to see an indicator on the query when it matches the querqy rule.

**Describe alternatives you've considered**
One alternative is more indicators on individual results to display the effect of a rule.

**Comment by epugh** [comment]
Okay, so here's a quick in progress screenshot.  two of these queries invoke Querqy rules..  
![image](https://github.com/user-attachments/assets/cdccfe08-19c4-49c3-bca9-9083ecf41ab8)

**Comment by epugh** [comment]
<img width="600" alt="image" src="https://github.com/user-attachments/assets/0d093122-5f67-4034-821a-ef8118823c2b">

refinining the UI

**Comment by epugh** [comment]
Done!  And live on app.quepid.com
