### ISSUE TITLE
Nested integer field does not display

### ISSUE THREAD

**Issue by rjurney** [o19s/quepid#106]
**Describe the bug**

I have a nested object in my data called foo_obj and my documents look like this:

```json
{
    "id": "uuid",
    "name": "cat",
    "foo_obj": {
        "foo_metric": 11,
        "foo_number": 55
    }
}
```

These are encoded in my `schema.xml` like so:

```xml
<fields>
    <field name="id"        type="string" stored="true" indexed="true" required="true" />   
    <field name="name" type="string" stored="true" indexed="true" required="true" />
    <field name="foo_obj.foo_metric"    type="int" stored="true" indexed="true" />
    <field name="foo_obj.foo_number" type="int" stored="true" indexed="true" />
</fields>
```

When I enter these nested fields, `foo_obj.foo_metric` and `foo_obj.foo_number` into Quepid's `Settings --> Displayed Fields`, they do not show up in the UI for the documents. Instead the values are blank. 

![image](https://user-images.githubusercontent.com/42149/78063451-14601400-7345-11ea-94b3-1cc6eda26af1.png)

**To Reproduce**

1. Create documents with a nested object
2. Load them into a Solr core with an appropriate schema (see above)
3. Create a new case in Solr to index this core
4. Add the nested fields (`foo_obj.foo_metric`, for example) to the list of fields to display
5. Run/Re-run searches
6. See the empty values for these nested int fields

**Expected behavior**
I expect nested integer fields (and float fields, but I haven't tried that) to display in Quepid document results.

**Screenshots**
See above.

**Additional context**
@dep4b was very nice to help us with identifying this problem :)

**Comment by epugh** [comment]
Just finished putting together a test solr index:
![Screenshot at Apr 25 15-54-13](https://user-images.githubusercontent.com/22395/80289545-141d2380-870d-11ea-90e9-cce1de9daac7.png)

**Comment by rjurney** [comment]
Cool!
