### ISSUE TITLE
Start app with a default admin account

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#107]
**Is your feature request related to a problem? Please describe.**
There seems to be no admin account available when running as a self-built docker image. You have to run `bin/docker r bin/rake db:seed:sample_users` first

**Describe the solution you'd like**
An admin user should be generated on db:init, with a random password. There should be a cmdline command to run to retrieve the admin user/password

**Comment by epugh** [comment]
I discovered that there are some additional command line tool called "Thor":  https://github.com/o19s/quepid/blob/master/README.md#thor

I haven't tried it at all.

**Comment by epugh** [comment]
I updated the docs (https://github.com/o19s/quepid/wiki/Installation-Guide#create-your-administrator-user) in preparation for Quepid 6.2.0 being released.   This has the `thor user:create` command that you want!
