### ISSUE TITLE
Firefox unhappy with Basic Auth

### ISSUE THREAD

**Issue by razilevin** [o19s/quepid#109]
**Describe the bug**

It appears as though using a url of the form `https://username:password@machine:9200/my_index/_search` will result in FireFox 74.0.1 "blocking" the request. The request does work in Chrome as expected so it is not a CORS issue. In addition if it was a CORS issue FireFox would display a CORS related error in the developers console.

To validate my findings I set a break-point in the the Angular `$HttpBackendProvider` function `createHttpBackend`, removed the username password part of the url and the request works as expected.

**Comment by CGamesPlay** [comment]
This is an issue in splainer-search, a downstream library. This PR fixes it. https://github.com/o19s/splainer-search/pull/79

**Comment by epugh** [comment]
I'm putting together a basic auth enabled Elasticsearch server for testing.  I did confirm that I can't make  the BASIC auth work, however it doesn't work for me in either Firefox or Chrome.  Going to try out the changes that @CGamesPlay did and test that.

**Comment by epugh** [comment]
@razilevin I'm still working on the next release of Quepid, however the fix was deployed on http://splainer.io if you want to give it a test with your Firefox!
