### ISSUE TITLE
When a try number is not specified for a case, automatically redirect to the most recent try

### ISSUE THREAD

**Issue by binarymax** [o19s/quepid#110]
Enable loading the latest “try” when I go to a case without specifying the try number.

For example if case number 9999 has 16 tries, and I go to http://app.quepid.com/case/9999/ …then it would automatically redirect to http://app.quepid.com/case/9999/try/16

**Comment by epugh** [comment]
Just tested, and yes I can duplicate it.   Oddly, if your last case was http://app.quepid.com/case/9999/try/16, and you go to app.quepid.com, it redirects to the whole thign!
