### ISSUE TITLE
Export and Import Judgements in the RRE Format

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#133]
I'm frustrated that I can't take my judgements in Quepid and export them to RRE for running at Scale.   And vice versa, I'd like to import judgements from RRE into Quepid so I can actively play with the search parameters in the quepid interface.

**Describe the solution you'd like**
Export/Import loop in the RRE .json format.   Export in the style that is closet to RRE, ie without the query group stuff, and then in import, take a RRE .json and get it to Quepid style.

**Describe alternatives you've considered**
I thought about exporting a Quepid Case into a complete RRE entity, but I think that involves too many different concepts.

**Additional context**
This is part of my Explorer project for 2020 to get the open source relevancy projects to all work together better!   Buff off the rough edges in getting them to cooperate.

**Comment by epugh** [comment]
Hey @agazzarini I thought you might be interested in this ticket ;-)

**Comment by agazzarini** [comment]
Wow! Absolutely, if I can help in some way, just give me a shout!

**Comment by epugh** [comment]
i've got the API side done, now on to the front end gui.
