### ISSUE TITLE
QScore Graph is Janky

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#140]
**Describe the bug**
The QScore Graph doesn't behave in a way that makes sense to a user with the new classical scorers AP, DCG, NDCG etc.   

Sometimes the colours make sense, but then you do a new rating and they don't.   

**To Reproduce**
Just go and play with it!   

**Expected behavior**
The graph over time should make sense!   Maybe we would want to inject a annotation every time the scorer get changed on a case since that chnages the numbers?

Something to think about for the future is if we track scorers over time with the scorer used, and I could see having multiple lines reflecting multiple scorer types.   Someday Quepid will support multiple scorers!

**Screenshots**

**Additional context**
The old V1 Scorer and the QScore worked together fine, and I think the graph is tied to the idea of a 1 to 10 scorer...?   Introduced with the merge of #100

**Comment by nathancday** [comment]
From what I can tell so far is this is linked to the scorer attribute `maxScore`

**Comment by synhershko** [comment]
FWIW I would just implement support for showing multiple scorers (https://github.com/o19s/quepid/issues/51) and then show a separate graph per scorer results whenever such exists, in different colors

**Comment by epugh** [comment]
See PR #150
