### ISSUE TITLE
FAQ addition about port forwarding?

### ISSUE THREAD

**Issue by flaxsearch** [o19s/quepid#141]
Marek Czarnecki <marek@czarnecki.biz> reports:

"But, during setup, I ran into a brick wall. I connect to an AWS Elastic Search cluster, commercially sensitive and locked in a private subnet.

Tried for ages to reconfigure to let your web app connect.

Then the solution was suggested to me:

    I am already running a local ssh port forward into the cluster, and your app runs locally to my machine in the browser context.

    ... So just set the URL to https://localhost:9200/<index>/_search

How do you feel about adding this to your FAQ or somewhere?

"

**Comment by epugh** [comment]
Fixed in 
https://github.com/o19s/quepid/wiki/Troubleshooting-Elasticsearch-and-Quepid#setup-ssh-port-forwarding-to-a-locked-down-cluster
