### ISSUE TITLE
Not able to run with pgsql and docker

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#155]
**Describe the bug**
Trying to use a Postgres DB for docker-compose is hard and fails.

**To Reproduce**
1. Create a pgsql db somewhere (not in docker)
2. Modify docker-compose.prod.yaml to point to that DB (with app image from hub)
3. Start the app (docker-compose up)
4. Fails because 'pg' db driver is not bundled in `o19s/quepid`
5. Clone `Dockerfile.prod`, `Gemfile` and `config` locally, add `pg ~> 0.18` to Gemfile (and Gemfile.lock) and modify docker-compose file accordingly (see [Dockerfile](https://gist.github.com/janhoy/70eed85ced5aaf8f6728074b3b7a5d67#file-dockerfile))
6. Build container and try again
7. Now we get started, to the point where `db:setup` is run
8. db setup fails with (see [full log](https://gist.github.com/janhoy/70eed85ced5aaf8f6728074b3b7a5d67#file-log-txt))
    ```
    rake aborted!
    ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "user_id" already exists
    : CREATE  INDEX  "user_id" ON "cases" USING btree ("user_id")
    ```

**Expected behavior**
* Docker image should ship with the most common db drivers including postgres, oracle etc
* DB `schema.rb` and migrations should work across different databases

**Comment by janhoy** [comment]
No urge to fix this, I gave up and use a standalone MySql instead, which btw worked like a charm :)

**Comment by epugh** [comment]
My feeling is that the type of database is kind of an internal detail to Quepid...  Kind of like when Solr went from a WAR deployable in Tomcat or Jetty to the servlet container being a internal detail to Solr.   Supporting multiple databases would require a much more comprehensive CI process than we have today ;-)

**Comment by janhoy** [comment]
Ok, that can be a choice you make. If so, I'd document it clearly and remove `DB_ADAPTER` variable from docker-compose and instead hardcode it in `database.yml` with a comment that it will NOT work with anything else.

Where I'm coming from is we plan to deploy Quepid as a container in our environment, but at the same time we don't want to keep the DB on the same host where it can get lost. We use ECS for containers and RDS for databases. It worked fine once I provisioned a MySql  RDS db.

**Comment by epugh** [comment]
Interesting on the DATABASE_URL versus teh DB_HOST etc..  I don't know why it's like that, though I think it's a pattern that I've seen...  not sure why!

**Comment by epugh** [comment]
Added a comment about AWS RDS to https://github.com/o19s/quepid/wiki/Installation-Guide#docker-compose-based-install
