### ISSUE TITLE
Errors during migration from 6.1.1 to 6.2.0

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#160]
**Describe the bug**
DB migrations fail with rake when migrating from 6.1.1 to 6.2.0.

**To Reproduce**
1. run `bin/docker r bundle exec rake db:migrate`

**Expected behavior**
Migrations should succeed

**Additional context**

Complete output for rake db:migrate

bin/docker r bundle exec rake db:migrate
Starting quepid_db ... done
Starting quepid_redis ... done
== 20200313204611 DropDefaultFromDefaultScorer: migrating =====================
-- remove_column(:default_scorers, :default)
   -> 0.0787s
== 20200313204611 DropDefaultFromDefaultScorer: migrated (0.0788s) ============

== 20200314193226 DropCommunalFromScorers: migrating ==========================
-- remove_column(:scorers, :communal)
   -> 0.0304s
== 20200314193226 DropCommunalFromScorers: migrated (0.0306s) =================

== 20200413184942 RenameUsersUsernameToEmail: migrating =======================
-- rename_column(:users, :username, :email)
   -> 0.0095s
== 20200413184942 RenameUsersUsernameToEmail: migrated (0.0097s) ==============

== 20200428150211 UpdateDemoSolrEsToNonDefaultPorts: migrating ================
== 20200428150211 UpdateDemoSolrEsToNonDefaultPorts: migrated (0.0909s) =======

== 20200517162038 MigrateUserDefaultScorer: migrating =========================
-- foreign_keys("users")
   -> 0.0022s
-- remove_foreign_key(:users, {:column=>:default_scorer_id})
   -> 0.0068s
-- add_column(:scorers, :communal, :boolean, {:default=>false})
   -> 0.0307s
== 20200517162038 MigrateUserDefaultScorer: migrated (0.0434s) ================

== 20200517162819 AddNewDefaultScorers: migrating =============================
== 20200517162819 AddNewDefaultScorers: migrated (0.1832s) ====================

== 20200517164239 AddFkToScorers: migrating ===================================
-- remove_column(:users, :scorer_id)
   -> 0.0378s
-- add_foreign_key("users", "scorers", {:column=>"default_scorer_id"})
   -> 0.0428s
== 20200517164239 AddFkToScorers: migrated (0.0809s) ==========================

== 20200522215022 RemoveScorerType: migrating =================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = ' at line 23: 
      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 1

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =1 and scorer_type = 'DefaultScorer'

      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 2

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =2 and scorer_type = 'DefaultScorer'

      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 3

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =3 and scorer_type = 'DefaultScorer'

      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 4

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =4 and scorer_type = 'DefaultScorer'

      // check that everything migrated
      // select count(*) from cases where scorer_type = 'DefaultScorer'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/usr/local/bundle/gems/rack-mini-profiler-2.0.1/lib/patches/db/mysql2.rb:22:in `query'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/srv/app/db/migrate/20200522215022_remove_scorer_type.rb:10:in `change'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:980:in `each'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:980:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = ' at line 23: 
      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 1

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =1 and scorer_type = 'DefaultScorer'

      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 2

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =2 and scorer_type = 'DefaultScorer'

      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 3

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =3 and scorer_type = 'DefaultScorer'

      INSERT INTO scorers (
        code,
        name,
        scale,
        manual_max_score,
        manual_max_score_value,
        show_scale_labels,
        scale_with_labels,
        created_at,
        updated_at
      )
      SELECT  code,
      name,
      scale,
      manual_max_score,
      manual_max_score_value,
      show_scale_labels,
      scale_with_labels,
      created_at,
      updated_at
      FROM    default_scorers WHERE id = 4

      SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = @last_id_in_scorers, scorer_type = 'Scorer' where scorer_id =4 and scorer_type = 'DefaultScorer'

      // check that everything migrated
      // select count(*) from cases where scorer_type = 'DefaultScorer'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/usr/local/bundle/gems/rack-mini-profiler-2.0.1/lib/patches/db/mysql2.rb:22:in `query'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/srv/app/db/migrate/20200522215022_remove_scorer_type.rb:10:in `change'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:980:in `each'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:980:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @last_id_in_scorers = LAST_INSERT_ID();

      update cases set scorer_id = ' at line 23
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/usr/local/bundle/gems/rack-mini-profiler-2.0.1/lib/patches/db/mysql2.rb:22:in `query'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/srv/app/db/migrate/20200522215022_remove_scorer_type.rb:10:in `change'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:980:in `each'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:980:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by epugh** [comment]
Can you confirm you are using the production docker image?   I think I ran into the same thing, and need to push up some changes to the Docker image...   I wonder if I should just do it, or do a 6.2.1...

**Comment by DmitryKey** [comment]
@epugh what I did was a fresh checkout of the v6.2.0 tag, running `bundle install` and then the migrate command above. I.e. I did *not* deploy from docker image. But this is what I would like to do next: deploy from the prod docker image into kubernetes and run the db migration for the same version transition: 6.1.1 -> 6.2.0.

**Comment by epugh** [comment]
So, the good news is, easy fix for you, which is go ahead and checkout `master` and then do the rest.   I had to make a1fc942d32e3d524836492f745735ce4ec4972ff and 029dd0cafe8caa492095c9483617b623a6a4e437 and 1a3c997f59b144a1cbffa59a04c67cb3e051b32d post cutting 6.2.0.  I guess I should try and do 6.2.1..  I'll get on that....

**Comment by DmitryKey** [comment]
thanks for a quick fix Eric!
I have successfully migrated the db, all in kubernetes.

Next I've noticed another issue with a custom scorer that was created under 6.1.1. It has 4 labels (1 through 4), but applying to a case still shows labels 1-10. The case however contains previously assigned labels with value=10. May be a warning could be shown in this case, that applying a more restrictive label-wise scorer needs adjusting existing labels. Furthermore, adjusting the labels did not change the behaviour of the label pop-up: it continues to show labels 1-10. Should I file a separate ticket?

**Comment by DmitryKey** [comment]
one more thing noticed: an Administrator user created under 6.1.1 shows as an ordinary user after db migration in 6.2.0. I judged by looking at the user menu pop-down when clicking on the user in top right corner: for an admin it shows an extended list of items: "Admin Home", "Users", "Quepid Scorers" and "Job Manager". But for the said admin I only see "My profile" and "Log out".

**Comment by epugh** [comment]
Can you check in the users table?   `users.administrator` should be 1.   We didn't change anything in the schema related to users from 6.1.1 to 6.2.0.    This makes me think something else "interesting" might have happened.

**Comment by epugh** [comment]
as far as the labeling, please do file a sepeate ticket.   
There *definitly* is an issue where if you rate your documents on one scale, and then change your scorer to another scale, you still have the ratings on the preior scale...    

I'm not sure the best solution..    I'm leaning toward encouraging folks to using a graded scale, like 0 to 4..   Then changing the binary scorers, like P and AP to downconvert the 0 to 4 to a 0/1 scale.   So 0 and 1 would be a 0.   and 2 would be ???  and 3 and 4 would be a 1 in binary scale.    

Messaging about this would be valuable.   

If you were to build a pure judgemetn collection UI, you would ask folks to rate, and the choice of the rating wouldn't be coupled to the scorer used!  So maybe we need to break that apart...

Thoughts on this?   Please do open another ticket.

**Comment by epugh** [comment]
BTW, I am on vacation for a week, so will come back and get working on this the week of the 28th ;-)

**Comment by DmitryKey** [comment]
I will create the ticket soon :) and we can come back to this once you are back!
Enjoy your vacation Eric :)

**Comment by epugh** [comment]
@DmitryKey is there anything that we need to work on together on this ticket, or can it be closed?

**Comment by DmitryKey** [comment]
@epugh one last bit, following your suggestion:

> select email,administrator from users where email="administrator";
+---------------+---------------+
| email         | administrator |
+---------------+---------------+
| administrator |             0 |
+---------------+---------------+
1 row in set (0.00 sec)

so I did the following on the mysql node:

`update users set administrator=1 where email="administrator";`

and that has fixed the issue.

![Screenshot 2020-08-28 at 13 56 35](https://user-images.githubusercontent.com/123553/91553612-5f06ac00-e936-11ea-9ab6-458673bf092d.png)

Thanks!
