### ISSUE TITLE
Scorer / labels disagreement

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#161]
**Describe the bug**
I've noticed the issue with a custom scorer that was created under 6.1.1, when tested in quepid migrated to the v6.2.0. 
The scorer has 4 labels (1 through 4), but applying to a case still shows labels 1-10. The case however contains previously assigned labels with value=10. Furthermore, adjusting the labels to 1-4 scale did not change the behaviour of the label pop-up: it continues to show labels 1-10.

May be a warning could be shown in this case, that applying a more restrictive label-wise scorer needs adjusting existing labels. 

**To Reproduce**
1. Create a scorer with a custom 1-4 label scale
2. Create a case and annotate some documents with labels on the 1-10 scale
3. Apply the scorer from 1.
4. Notice that label popup does not change to 1-4 scale.
5. Change all labels of the case to be inside 1-4 scale. Label pop-up continues to show scale 1-10.

**Expected behavior**
1. Warning message, that this case is of different scale (broader or narrower).
2. Ability to rectify the existing labels. It could be a pop-up with manual mapping. For instance if scale 1-10 to be downgraded to 1-4, then show a mapping table:

1 --> ___
2 --> ___
...
10 --> ___

or even, let the user type a javascript with a custom mapping function. Happy to discuss this further!

**Comment by nathancday** [comment]
Just to confirm so behavior from when I try to replicate:

When a scorer is selected with more restrictive labels (moving to 1-4 from 1-10) the values outside of the range become greyed-out/inactive. But when you click the scorer to re-rate, you get the new scale options only (so 1-4). Is that what you experience?

**Comment by epugh** [comment]
@DmitryKey @nathancday I'm coming back to thinking on this one...      I'm going to try and mock up some screens that show some behaviors...

I really like the idea that we have some sort of conversion at scoring time from "whatever judgements scale you used" to a "whatever scale the scorer needs".
