### ISSUE TITLE
Button to toggle only rated docs

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#163]
**Describe the solution you'd like**
Our usecase is not a typical top-10 tuning. We will rate several documents throughout the result set, and our custom scorer will only give a small boost for a high position. We need to measure that certain hits far down the list which have a low rating do not climb too high due to a tuning.

Thus we propose to add a "View only rated" button to each query view, see screenshot:
![only-rated](https://user-images.githubusercontent.com/409128/85275567-cc064d00-b480-11ea-9d0a-24d85a73515d.png)

Pressing this button will, instead of showing top-N docs, instead show top-N-rated-docs, in the correct score order from the query. Thus if we have rated hit 1, 20, 40 and 100, then we'd show those 4 documents. We'll use both explain-other and paging to pick docs to rate, and expect them to then show up in the "rated" list. Note that the query must not be filtered on the doc-IDs, since we'll then lose the original hit position, which may be part of the ranking formula. So this is more of a display-time filtering. Perhaps the code needs to fetch a large number of results and just display the ones that are in the list of rated docs?

**Describe alternatives you've considered**
Adding a `fq` to the query with a list of IDs, but that will discard the hit position.

**Comment by nathancday** [comment]
This is a cool idea. I've been thinking of it from the angle of managing the docs rated in "Explain Missing", because right now we can't easily see what has been rated there. I'm not sure I understand you use case exactly, but seeing rated docs (or hiding unrated docs) would be nice for visual management.

First take, I think combing docs from Explain Missing and engine results might be tricky. Quepid today is displaying results that are retrieved by the engine. While you can rate docs outside of the results with "Explain Missing", these are never actually scored by the engine. Would "other" docs be assigned a score of zero and added onto the end of the "real" docs for position?

**Comment by janhoy** [comment]
If the display and scoring logic is separate, then just filtering on rated IDs in the query that pulls the hits to display would do the trick. I'm not that into the code to know whether the list of docs to calcuate scores is separate from the list retrieved for display.

Also showing rated docs that don't match the query is a separate issue, but also very useful. We could easily include them in the main query (if requested with a toggle), by pulling them with an OR clause with score==0 forced.

**Comment by janhoy** [comment]
I had a look at the JS for running queries for a case. Seems like the actual query to the engine is delegated to `splainer-search`, making it somewhat more complicated to hook into the search loop for e.g. doing a pre-query to fetch positions and a filter the main query by list of rated doc-IDs. I think the main query needs an ID filter for paging etc to work as expected, and also for performance reasons.

Also, I realize that we fetch reqults from all queries in a case in the same call, so perhaps the "View only rated" button belongs on the case level and not on the query level.

**Comment by janhoy** [comment]
Here is a sample of how this could be a checkbox on the case level instead of on each query
![only-ratings-2](https://user-images.githubusercontent.com/409128/90023799-70a05080-dcb4-11ea-990a-6e0bd214c98c.png)

**Comment by epugh** [comment]
This continues to be in progress!

**Comment by epugh** [comment]
This feature is in preview at https://quepid-pr-229.herokuapp.com/secure/

**Comment by epugh** [comment]
Fixed in #229
