### ISSUE TITLE
Query notes don't allow fast typing

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#164]
**Describe the bug**
Typing in a normal (fast?) way in the query notes (Toggle Notes feature) -- I get part of text removed with auto-save.

**To Reproduce**
1. Go to a query case
2. Click 'Toggle Notes'
3. Begin typing with normal pace -- observe how some text disappears

**Expected behavior**
All text typed remains.

**Screenshots**
![Screenshot 2020-06-24 at 12 51 50](https://user-images.githubusercontent.com/123553/85533808-84ff8f80-b619-11ea-9d98-0ab4eac6f4b3.png)

Here I typed: "How is it going"

**Additional context**
Perhaps a better way would be to not auto-save, but instead have a traditional button Save -- could be easier to implement.
Of course, auto-save is a nifty feature to have -- if can be fixed.

**Comment by nathancday** [comment]
Ooof, just checked on my machine and can confirm that is truly painful.

I think you are right to move away from auto-save to a save button. Thanks for flagging we will look at it!

**Comment by DmitryKey** [comment]
thanks @nathancday !

**Comment by epugh** [comment]
Okay, I've opened a PR that restores the old Save Notes button:
![Screenshot at Jul 03 14-19-07](https://user-images.githubusercontent.com/22395/86491244-41eb9d80-bd38-11ea-9152-bcab7265fedb.png)

So here is a question, if you don't click the "Save Note" button, then your changes are lost.  Do you think the Toggle button should autosave the notes?   Or is the button good enough for now?

**Comment by epugh** [comment]
Going to close with the Save Notes button for now.

**Comment by DmitryKey** [comment]
Fantastic work, guys!
