### ISSUE TITLE
Add OAuth providers (Github)

### ISSUE THREAD

**Issue by gregoryduckworth** [o19s/quepid#188]
**Is your feature request related to a problem? Please describe.**
Rather than having multiple passwords to remember, it would be nice if there was the ability to login with providers such as Github.

**Describe the solution you'd like**
Github OAuth implemented so user management could be done with that.

**Describe alternatives you've considered**
Having the current implementation and having to remember passwords.

**Additional information**
Having the ability to use something like [OmniAuth](https://github.com/omniauth/omniauth/wiki) would allow multiple providers to be used.

**Comment by epugh** [comment]
@gregoryduckworth thank you for opening this issue.  

I agree that having more flexible authentication options would be great.  Today you can't authenticate via just the API, which means you have to click through the GUI.  Hence the awkward lines here in AgentQ: https://github.com/o19s/agent_q/blob/master/lib/agent_q.rb#L30.   

Doing this isn't on my roadmap, but I'd love to see the addition to Quepid!

**Comment by epugh** [comment]
Ironically, when stalebot tagged this, is the same weekend I finally made progress on Rails upgrade from 4.2 --> 5.   We use Devise for user auth, and it has a number of "providers" including oauth.  We need to upgrade Rails in order to open the door to using the newer Devise code for both features like this, and what I am driving for, the ability to invite people to teams in Quepid who haven't yet signed up!

**Comment by gregoryduckworth** [comment]
> Ironically, when stalebot tagged this, is the same weekend I finally made progress on Rails upgrade from 4.2 --> 5. We use Devise for user auth, and it has a number of "providers" including oauth. We need to upgrade Rails in order to open the door to using the newer Devise code for both features like this, and what I am driving for, the ability to invite people to teams in Quepid who haven't yet signed up!

That is great to hear @epugh!

**Comment by epugh** [comment]
Hey @gregoryduckworth I wanted to ping you about your bandwidth/energy/interest on potentially adding this?   I'm going to be merging in PR #256 and then #259 soon.   This would set you up to do the oAuth providers work if you were interested?

**Comment by epugh** [comment]
@gregoryduckworth I wanted to let you know that those two tickets were merged, and if you wanted to add the oAuth support, that is now doable now that we have Rails 5 live!

**Comment by epugh** [comment]
I've started simplifying the login pages and the user profile pages to not touch the Angular app front end, but to be plain vanilla Rails / server side HTML.   Once that is done, I'll probably come back and finish adding #280
