### ISSUE TITLE
Elasticsearch 7 returns total hits in different format that Elasticsearch 5 and 6

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#19]
**Describe the bug**
Elasticsearch 7 returns total hits in different JSON format than ES 5 and 6, which leads to odd rendering in the GUI.

**To Reproduce**
1. Create a sample case in Quepid, and use ES 7: http://quepid-elasticsearch.dev.o19s.com:9207/tmdb/_search
2. Run a query, see the `{"value":130,"relation":"eq"} Results` text.
3. Swap to ES 6 via http://quepid-elasticsearch.dev.o19s.com:9206/tmdb/_search
4. Run same queryies, but the JSON will go away showing just `130 Results` text

**Expected behavior**
Just show me the number!

**Screenshots**

<img width="509" alt="Screenshot at Nov 05 22-59-22" src="https://user-images.githubusercontent.com/22395/68267295-f30e2c80-001f-11ea-8b8b-91e705b56def.png">

**Comment by epugh** [comment]
See this documentation: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html

We don't handle the `relation` key...
```
{
    "_shards": ...
    "timed_out": false,
    "took": 100,
    "hits": {
        "max_score": 1.0,
        "total" : {
            "value": 2048,    
            "relation": "eq"  
        },
        "hits": ...
    }
}
```

**Comment by epugh** [comment]
Okay, turns out, to fix the formatting, we need to go to our good friend https://github.com/o19s/splainer-search/ to fix this.  I opened a issue https://github.com/o19s/splainer-search/issues/69 to track it.  When `splainer-search` 2.5.1 comes out, this bug will be fixed.  

I am burying the whole relation idea that ES gives, and maybe in the future we want to highlight approximite hits versus exact....

**Comment by synhershko** [comment]
Relation will just return an approximate round number for large result sets. It's just a matter of displaying the exact number if relation == "eq" or ~number otherwise.

**Comment by epugh** [comment]
@synhershko thanks for the comment.   I ended up going with this fix: https://github.com/o19s/splainer-search/pull/71/files This was easier than extending Splainer Search to support the idea of exact versus approximate result count.   Having said that, if you'd like to add that as a capability to Splainer-search, then we could add it to Quepid and Splainer, that would be welcome.

**Comment by synhershko** [comment]
That'd work!

**Comment by epugh** [comment]
Tried to release fix last night but had some issues.
