### ISSUE TITLE
Rating from keyboard

### ISSUE THREAD

**Issue by peterdm** [o19s/quepid#190]
**Is your feature request related to a problem? Please describe.*
Quepid Tunnel Syndrome (Vision?) is a repetitive stress injury related to poor hand position on mouse and keyboard exacerbated by multiple small repetitive movements (e.g. mousing to a drop-down, clicking it, mousing down to the desired selection, clicking it, and scrolling to the next result, repeat [0..1000])

**Describe the solution you'd like**
The top-most visible query or result would receive focus in the absence of other input.  There would be a visible indication as to which query or result had focus.

**Keyboard keymap:**
`<Up-Arrow>` Shift focus to the next result or query above the current one in focus and scroll into view if necessary
`<Down-Arrow>` Shift focus to the next result or query below the current one in focus and scroll into view if necessary
`<Right-Arrow>` If closed query in focus, open it
`<Left-Arrow>` If result in focus, close the containing query.  If open query in focus, close it.
`1`, `2`, `3`, `4` etc... If result in focus, set this as the judgement.  If query in focus, ensure it is open, and prompt to confirm that user wants to grade all results with this judgement.

**Describe alternatives you've considered**
Taking a long break from using Quepid.

**Additional context**

**Comment by epugh** [comment]
Feeling this issue this morning!
