### ISSUE TITLE
Rename the "Export Case" and "Import Ratings" to just "Export" and "Import"?

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#195]
<img width="510" alt="Screenshot at Aug 28 12-17-20" src="https://user-images.githubusercontent.com/22395/91590076-c158b000-e928-11ea-8d08-d627818852ee.png">

**Is your feature request related to a problem? Please describe.**
As we've beefed up the Export and Import functions in Quepid to handle roundtripping data better, I notice that the labels that we are using might not be accurate anymore...

"Export Case" lets you export case data, query data, and ratings....   

"Import Ratings" lets you import rating data, but also lets you import just raw set of queries as well.    

**Describe the solution you'd like**
I'm thinking to rename to just *Export* and *Import*...   and move them to next to each other.

**Describe alternatives you've considered**
Thought about "Export Queries" and "Import Queries" or "Export Data" and "Import Data".

**Comment by epugh** [comment]
Argh I just fx this

**Comment by abhishekChoudhary93** [comment]
Can I take this up ?
