### ISSUE TITLE
Redo bin/setup_docker and bin/docker to be more friendly to new people.

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#199]
**Is your feature request related to a problem? Please describe.**
In pairing with @brigaldies I noticed that he was a bit confused why we were running a ./bin/docker...  Something like "I already have docker installed"...

We don't use bin/docker for production setups, it's primarily just a wrapper for development which requires you to have Ruby installed on your box.   

I'm wondering if a different name would make better sense?   

Some ideas...

`./bin/quepid` and `./bin/setup_quepid` <-- Would make sense maybe if you used this to fire up a Production Quepid as well, so I don't love this one.

`./bin/quepid-dev` and `./bin/quepid-dev` <-- Little more verbose, but has dev in the name.

`./bin/development` and `./bin/setup-development`.

Also thinking maybe the code in `./bin/setup_docker` just moves into the main `./bin/docker` script as a parameter: `bin/docker setup_development`.

Thoughts?

**Comment by worleydl** [comment]
Can we get more into a pure docker-compose setup instead of requiring rails to get started?  Renaming may make sense as well.

**Comment by epugh** [comment]
This makes sense to me.   nothing in `setup_docker` or `docker` needs to be rAils versus .sh

**Comment by epugh** [comment]
Running into this again.   We need to convert these to Bash and maybe powershell equivlaetns.
