### ISSUE TITLE
Integrate Quepid with Anserini as a 3rd engine

### ISSUE THREAD

**Issue by rjurney** [o19s/quepid#212]
**Is your feature request related to a problem? Please describe.**

It would be cool to integrate directly with Anserini to help refine search models without running a full-blown search engine.

**Describe the solution you'd like**

I am not sure. I want to be able to hand rank queries with Anserini... but I do not have a clear view of how the integration would work. I suppose you would setup queries in Anserini and then collect ranked data over them? I am an Anserini neophyte.

**Describe alternatives you've considered**

Anserini search models can be exported/integrated into SolrCloud, so things could be done that way. But I've never done this.

**Comment by epugh** [comment]
I've been playing with a proxy based on expressjs to convert search results from one format to another, so you could do a Answerini --> Solr or Answerini --> ES conversion, and then have Quepid use that.   I'm going to publish the code later this month.
