### ISSUE TITLE
In TLRE class we use a set of settings, lets have that set on tmdb by default

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#224]
**Is your feature request related to a problem? Please describe.**
Why not have the default settings for the TMDB dataset use all the standard settings in the TLRE class.

**Describe the solution you'd like**
All the various overview, genre fields should be in the default.

**Describe alternatives you've considered**

**Additional context**
@nathancday can you provide what we think of the canonical set of fields for Solr class and ES class?

**Comment by epugh** [comment]
Pulled from the class: `id:id, title:title, tagline, overview, text_people, release_date, vote_count, vote_average, genres`

**Comment by epugh** [comment]
@nathancday Wanted to ping you again, can you give me the defrault settings for the TLRE class?

**Comment by nathancday** [comment]
I think that it a solid list you have above. I don't think there is a "gold" standard but those are the big ones.
