### ISSUE TITLE
AP@10 

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#225]
**Describe the bug**
With AP, we had the query `the big lebowski` where we added `&defType=edismax&mm=100%`, and now get 1 perfect result.  We get a green box, but a score of .20, but should be a score of 1.  

**To Reproduce**
1. Use the TMDB
2. Add `the big lebowski`
3. rate and snapsho.
4. change structure to &defType=edismax&mm=100%
5.  Look at the new score.

**Expected behavior**
Should be a 1 and green.  This assumes that AP@10 with 1 result only is a 1, and not a .10

**Screenshots**

**Additional context**

**Comment by nathancday** [comment]
Coming back to this from @234, but I can no reproduce this behavior. Seems to work as expected, possibly already fixed elsehwere?
<img width="310" alt="Screen Shot 2020-11-09 at 2 22 05 PM" src="https://user-images.githubusercontent.com/808225/98586783-3afd0a80-2297-11eb-9a7b-68c2b5fc6be2.png">

**Comment by nathancday** [comment]
Ignore my comment above, this is a bug that occurs when result sets are less than K/10, I updated the AP@10 score seed code to fix it.
