### ISSUE TITLE
Display result for suggested query 

### ISSUE THREAD

**Issue by doantranthanh** [o19s/quepid#226]
hi all,

I am using Quepid on my local.  It is working well with Query. However when I tried with Suggest query such as

````
{
  "suggest": {
    "text": "dimissals",
    "simple_phrase": {
      "phrase": {
        "field": "Title.trigram",
        "max_errors": 0.8,
        "confidence": 2.1,
        "direct_generator": [
          {
            "field": "Title.trigram",
            "suggest_mode": "always"
          },
          {
            "field": "Title.reverse",
            "suggest_mode": "always",
            "pre_filter": "xperthr_reverse_analyzer",
            "post_filter": "xperthr_reverse_analyzer"
          }
        ],
        "highlight": {
          "pre_tag": "<em>",
          "post_tag": "</em>"
        },
        "collate": {
          "query": {
            "source": "{ \"match\": { \"{{field_name}}\": {\"query\":\"{{suggestion}}\",\"operator\":\"AND\"}}}"
          },
          "params": {
            "field_name": "Title.trigram"
          },
          "prune": true
        }
      }
    }
  }
}
````

The suggest query run successfully but I dont know how to display the results. It looks like

![image](https://user-images.githubusercontent.com/9557564/96573371-f4cf0f80-12c5-11eb-90bc-e516e0242b8c.png)

How can I display the results?

Thanks

**Comment by epugh** [comment]
This is a great question!   So right now we use a library called splainer-search (https://github.com/o19s/splainer-search/)  as a wrapper around both Solr and ES queries.  It doesn't know about the response from a Solr Suggestor, though it probably SHOULD!   

We need to do a refactoring of splainer-search to make it easier to wrap any kind of Solr query (and other search engines), and convert the results to a canonoical format that can be rendered by Quepid.   ( note this @worleydl ;-) )

So, in the short term, I recommend you look at i_spy (https://github.com/epugh/i_spy), which is a proxy that converts search results from a source to a Solr formatted response.   If you add a Suggestor Format --> Solr Response Format to i_spy, let me know, I'd lvoe to add it.    I also do the same thing for taking a query, and returning the facets for judging how good the facets are!

**Comment by doantranthanh** [comment]
Thank you for very quick reply.

I forgot to mention that I am using ElasticSearch suggested query so I will have a look at the 

https://github.com/o19s/splainer-search/

Not sure how can I use with Quepid now :).

**Comment by epugh** [comment]
;-)   Splainer-search is kind of a dark hole of Angular 1 code, so you may be better off using the i_spy way of jsut converting the results...     However, if you do dig into splainer-search, plese submit a Pull Request, I'd love to have that added.

**Comment by epugh** [comment]
Hey @worleydl is my understanding of the issue correct, or is there soemthing else?
