### ISSUE TITLE
Missing Authorization Check for Team Owner

### ISSUE THREAD

**Issue by testerTester0123456789** [o19s/quepid#230]
**Describe the bug**
A team member can become the team owner without authorization. By issuing a PUT request to "/api/teams/2/owners/3", any team member can become the team owner. This could allow an attacker to remove and add scorers, cases and other team members. It is recommended that authorization is checked so only the team owner can change the ownership role. Note that "2" and "3" will need to be changed to the appropriate team number and user number.

**To Reproduce**
1. Login
2. Send a PUT request as below:
```
PUT /api/teams/2/owners/3
~HEADERS~

{
}
```
**Expected behavior**
Only the Team owner should be able to change the Team Owner.

**Additional context**
Relevant code appears to be here. It appears there needs to be an authorization check before processing the request.
https://github.com/o19s/quepid/blob/0147f3133a4c42559acd43291a2c34fe738c11d8/app/controllers/api/v1/teams_controller.rb

**Comment by epugh** [comment]
This is now fixed!
