### ISSUE TITLE
Importing ratings from RRE returns 500 error

### ISSUE THREAD

**Issue by LiuCao0614** [o19s/quepid#244]
**Describe the bug**
In my local running Quepid, it returns 500 server error when importing ratings from RRE json file.

**To Reproduce**
1. Spin up a local Quepid
2. Create a new case and connect to a Elastic Search instance
3. In the dashboard, click "Import Ratings" -> "RRE" -> Choose a file -> "Import"
4. "Unable to import ratings from RRE: 500 - Internal Server Error" is returned

**Expected behavior**
RRE json file should be successfully imported

**Screenshots**
![image](https://user-images.githubusercontent.com/22570070/99320652-f508ef00-2820-11eb-9246-f00f2d562dff.png)

**Comment by epugh** [comment]
Ouch!!!!!!   Can you provide a suitability anonymized copy of the RRE formatted file?    This feature has worked for me, but I don't think we've really tested it with a wide variety of RRE sourced files, so it would be great to have yours.   Also, if you look in the README at the section on logs, can you see where it failed?  in dev do `bin/docker r tail -f -n 200 log/development.log` and prod do `bin/docker r tail -f -n 200 log/production.log`

**Comment by LiuCao0614** [comment]
My Quepid is connecting to an internal es instance in my company, so I may not be able to share that. But I did get some logs from Quepid docker:


06:31:29 web.1 | Processing by Api::V1::Import::RatingsController#create as JSON
06:31:29 web.1 | User Exists (0.7ms) SELECT 1 AS one FROM `users` LEFT OUTER JOIN `permissions` ON `permissions`.`user_id` = `users`.`id` WHERE `users`.`id` = 1 LIMIT 1
06:31:29 web.1 | User Load (0.5ms) SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
06:31:29 web.1 | Permission Load (0.4ms) SELECT `permissions`.* FROM `permissions` WHERE `permissions`.`user_id` IN (1)
06:31:29 web.1 | SQL (0.7ms) SELECT DISTINCT `cases`.`id`, `cases`.`id` AS alias_0 FROM `cases` LEFT OUTER JOIN `case_metadata` ON `case_metadata`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams_cases` ON `teams_cases`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams` ON `teams`.`id` = `teams_cases`.`team_id` LEFT OUTER JOIN `teams_members` ON `teams_members`.`team_id` = `teams`.`id` LEFT OUTER JOIN `users` ON `users`.`id` = `teams_members`.`member_id` WHERE ((`teams`.`owner_id` = 1 OR `teams_members`.`member_id` = 1) OR `cases`.`user_id` = 1) AND `cases`.`id` = 3 ORDER BY `cases`.`id` ASC LIMIT 1
06:31:29 web.1 | SQL (0.6ms) SELECT `cases`.`id` AS t0_r0, `cases`.`case_name` AS t0_r1, `cases`.`last_try_number` AS t0_r2, `cases`.`user_id` AS t0_r3, `cases`.`archived` AS t0_r4, `cases`.`scorer_id` AS t0_r5, `cases`.`created_at` AS t0_r6, `cases`.`updated_at` AS t0_r7, `case_metadata`.`id` AS t1_r0, `case_metadata`.`user_id` AS t1_r1, `case_metadata`.`case_id` AS t1_r2, `case_metadata`.`last_viewed_at` AS t1_r3, `teams`.`id` AS t2_r0, `teams`.`name` AS t2_r1, `teams`.`owner_id` AS t2_r2, `teams`.`created_at` AS t2_r3, `teams`.`updated_at` AS t2_r4, `users`.`id` AS t3_r0, `users`.`email` AS t3_r1, `users`.`password` AS t3_r2, `users`.`agreed_time` AS t3_r3, `users`.`agreed` AS t3_r4, `users`.`first_login` AS t3_r5, `users`.`num_logins` AS t3_r6, `users`.`name` AS t3_r7, `users`.`administrator` AS t3_r8, `users`.`reset_password_token` AS t3_r9, `users`.`reset_password_sent_at` AS t3_r10, `users`.`company` AS t3_r11, `users`.`locked` AS t3_r12, `users`.`locked_at` AS t3_r13, `users`.`created_at` AS t3_r14, `users`.`updated_at` AS t3_r15, `users`.`default_scorer_id` AS t3_r16, `users`.`email_marketing` AS t3_r17 FROM `cases` LEFT OUTER JOIN `case_metadata` ON `case_metadata`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams_cases` ON `teams_cases`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams` ON `teams`.`id` = `teams_cases`.`team_id` LEFT OUTER JOIN `teams_members` ON `teams_members`.`team_id` = `teams`.`id` LEFT OUTER JOIN `users` ON `users`.`id` = `teams_members`.`member_id` WHERE ((`teams`.`owner_id` = 1 OR `teams_members`.`member_id` = 1) OR `cases`.`user_id` = 1) AND `cases`.`id` = 3 AND `cases`.`id` IN (3) ORDER BY `cases`.`id` ASC
06:31:29 web.1 | Completed 500 Internal Server Error in 13ms (ActiveRecord: 2.9ms)

**Comment by epugh** [comment]
I just exported a case from the production (http://app.quepid.com) environment in the RRE format, and then re-imported it to the staging (http://staging-quepid.herokuapp.com) successfully.  I'm attaching the RRE export file format.  Can you diff yours to mine and see where the differences are?   Also, did you get anything from the development.log?   Are you running the production setup of Quepid Docker image, or the developer version?

**Comment by epugh** [comment]
Here is my .json file, I had to add a .txt file extension 
[OSC_blog_rre.json.txt](https://github.com/o19s/quepid/files/5560390/OSC_blog_rre.json.txt)
to get it to add to Github!

**Comment by LiuCao0614** [comment]
I think I figured out what's going on here. Basically I created a RRE format judgement list by running queries against index A, and I tried importing the generated judgement list into a case that set up with index B. That's the reason why I got 500 error. So it seems like when we import a RRE format judgement list, we need to make sure that the index field in the .json file matches the current connected index. Is it correct?

**Comment by epugh** [comment]
I don’t think we actually look at that field, however is it possible your
doc ids differ between the indexes?   We should deal with import issues and
at least give a nice error!

**Comment by epugh** [comment]
Actually, try exporting and then importing to a new case with same index...  I suspect it will work, which points to ids differing between index a and b.

**Comment by LiuCao0614** [comment]
Just tried exporting and importing to a new case. Yes it worked. I also tried modifying the index field and found out that it actually didn't affect the result(it still worked!)

**Comment by LiuCao0614** [comment]
I took a closer look at the RRE judgement list I used to repro the issue. Found something wrong in the doc ids. So this issue should be caused by input error, not from Quepid. But yes, it would be great that we can have error message that provides more context to users.

**Comment by epugh** [comment]
I have a branch that hardens the export import cycle...   hope to have it in removable state tomorrow

**Comment by LiuCao0614** [comment]
Thanks for working on it!

**Comment by epugh** [comment]
And by "removable" I mean "mergable" state!
