### ISSUE TITLE
New release for Quepid

### ISSUE THREAD

**Issue by LiuCao0614** [o19s/quepid#258]
Hey I wonder what is the plan for the release of new version?  There are some changes that fix injection issues committed recently. I'd like to know when are we able to use the latest version.

**Comment by epugh** [comment]
Thanks for the poke, been sitting o things for a while!  https://relevancy.slack.com/archives/CJ42JGQ6L/p1607431913091100

Would love another set of eyes on https://quepid-staging.herokuapp.com/secure/ and then release end of day today EST.

**Comment by LiuCao0614** [comment]
Cool thanks! Will take a look today.

**Comment by LiuCao0614** [comment]
Just did some smoke testing against the server you sent me. Created a new case and tested custom scorer, snapshot, comparing snapshot, importing and exporting, and rating queries. It worked as expected. Let me know if you need anything else from me.

**Comment by epugh** [comment]
Thanks!  getting started.

**Comment by epugh** [comment]
We have a release!  https://twitter.com/quepid_search/status/1336437756986331137

**Comment by LiuCao0614** [comment]
Cool! Thanks for working on it!
