### ISSUE TITLE
Store search-engine-query-syntax,  tuning knobs, and evaluation metric to improve snap-shot reproducability 

### ISSUE THREAD

**Issue by josephineHonore** [o19s/quepid#260]
Snaps-shot are good for comparing results, but as they don't include the search-engine-query-syntax, the tuning knobs, and the evaluation metric used te genrate the results stored in the snap-shot, reproducing and keeping track of experiments over time is difficult.  

**Describe the solution you'd like**
Storing experement input such as search-engine-query-syntax, tuning knobs, and the used evaluation metric as part of the snap-show, would allow you to reproduce results, and export all information required to reproduceresults, assuming the same data and index settings in elasticsearch.  

Being able to add "data version" or "index version" labels to a snap-shot would also be a nice to have feature.

**Comment by epugh** [comment]
@josephineHonore I'd love to see this feature added as well!   We're doing a class to help folks learn how to hack Quepid, https://twitter.com/quepid_search/status/1362834690248441862 for more info.

**Comment by epugh** [comment]
Hey @worleydl this ticket by @josephineHonore overlaps with what we are chatting about.
