### ISSUE TITLE
Quepid crashed when upgrading to 6.4.0

### ISSUE THREAD

**Issue by LiuCao0614** [o19s/quepid#264]
Hi Team! I'd like to ask a question about Quepid ruby logs. I have an AWS cluster set up to run Quepid application. It was working fine with version 6.3.2. Recently Quepid released 6.4.0 and I wanted to upgrade my application in AWS to the latest version. When I tried upgrading, I saw a crash in Quepid application pod, and here are the logs I got:

│ 23:42:48 web.1    | started with pid 8                                                                                                                │
│ 23:42:48 worker.1 | started with pid 9                                                                                                                │
│ 23:42:49 web.1    | [8] Puma starting in cluster mode...                                                                                              │
│ 23:42:49 web.1    | [8] * Version 3.12.0 (ruby 2.5.8-p224), codename: Llamas in Pajamas                                                               │
│ 23:42:49 web.1    | [8] * Min threads: 5, max threads: 5                                                                                              │
│ 23:42:49 web.1    | [8] * Environment: production                                                                                                     │
│ 23:42:49 web.1    | [8] * Process workers: 2                                                                                                          │
│ 23:42:49 web.1    | [8] * Preloading application                                                                                                      │
│ 23:42:51 worker.1 | Read-only file system @ rb_sysopen - /tmp/execjs20210112-9-gdrzq5js                                                               │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:55:in `initialize'                                             │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:55:in `open'                                                   │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:55:in `block in create_tempfile'                               │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tmpdir.rb:135:in `create'                                                                               │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:53:in `create_tempfile'                                        │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:61:in `write_to_tempfile'                                      │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:30:in `exec'                                                   │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'                                             │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'                                                             │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'                                                         │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'                                                          │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/uglifier-4.1.20/lib/uglifier.rb:154:in `initialize'                                                        │
│ 23:42:51 worker.1 | /srv/app/config/environments/production.rb:30:in `new'                                                                            │
│ 23:42:51 worker.1 | /srv/app/config/environments/production.rb:30:in `block in <top (required)>'                                                      │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `instance_eval'                                                │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `configure'                                                    │
│ 23:42:51 worker.1 | /srv/app/config/environments/production.rb:3:in `<top (required)>'                                                                │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'                                   │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'                          │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'                           │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'                                   │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'                            │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/engine.rb:597:in `each'                                                          │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/engine.rb:597:in `block in <class:Engine>'                                       │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'                                           │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'                               │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'   
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'                                 │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'                            │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'                                                │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'                                       │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'                                                    │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'                                        │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'                                                                                  │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'                                                │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'                                            │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'                                                                                  │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'                                                                                  │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'                                                     │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'                                                                            │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'                                                                            │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'                                        │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'                                              │
│ 23:42:51 worker.1 | /srv/app/config/environment.rb:7:in `<top (required)>'                                                                            │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'                                   │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'                          │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'                           │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'                                   │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:285:in `boot_system'                                                      │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/cli.rb:46:in `run'                                                               │
│ 23:42:51 worker.1 | /usr/local/bundle/gems/sidekiq-5.2.5/bin/sidekiq:12:in `<top (required)>'                                                         │
│ 23:42:51 worker.1 | /usr/local/bundle/bin/sidekiq:23:in `load'                                                                                        │
│ 23:42:51 worker.1 | /usr/local/bundle/bin/sidekiq:23:in `<top (required)>'                                                                            │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'                                                              │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'                                                       │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'                                                               │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'                                                                  │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'                                           │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'                            │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'                                             │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'                                                               │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'                                           │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'    
│ 23:42:51 worker.1 | /usr/local/bin/bundle:30:in `block in <main>'                                                                                     │
│ 23:42:51 worker.1 | /usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'                                      │
│ 23:42:51 worker.1 | /usr/local/bin/bundle:22:in `<main>'                                                                                              │
│ 23:42:51 web.1    | [8] ! Unable to load application: Errno::EROFS: Read-only file system @ rb_sysopen - /tmp/execjs20210112-8-1q746vljs              │
│ 23:42:51 web.1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)                                                                │
│ 23:42:51 web.1    | Errno::EROFS: Read-only file system @ rb_sysopen - /tmp/execjs20210112-8-1q746vljs                                                │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:55:in `initialize'                                           │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:55:in `open'                                                 │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:55:in `block in create_tempfile'                             │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tmpdir.rb:135:in `create'                                                                             │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:53:in `create_tempfile'                                      │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:61:in `write_to_tempfile'                                    │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:30:in `exec'                                                 │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'                                           │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'                                                           │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'                                                       │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'                                                        │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/uglifier-4.1.20/lib/uglifier.rb:154:in `initialize'                                                      │
│ 23:42:51 web.1    |   /srv/app/config/environments/production.rb:30:in `new'                                                                          │
│ 23:42:51 web.1    |   /srv/app/config/environments/production.rb:30:in `block in <top (required)>'                                                    │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `instance_eval'                                              │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `configure'                                                  │
│ 23:42:51 web.1    |   /srv/app/config/environments/production.rb:3:in `<top (required)>'                                                              │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'                                 │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'                        │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'                         │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'                                 │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'                          │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/engine.rb:597:in `each'                                                        │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/engine.rb:597:in `block in <class:Engine>'                                     │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'                                         │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'                                                   │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'                             │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'                                                                 │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'                               │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'                          │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'  
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'                                     │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'                                                  │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'                                      │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'                                                                                │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'                                              │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'                                          │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'                                                                                │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'                                                                                │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'                                                   │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'                                                                          │
│ 23:42:51 web.1    |   /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'                                                                          │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'                                      │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'                                            │
│ 23:42:51 web.1    |   /srv/app/config/environment.rb:7:in `<top (required)>'                                                                          │
│ 23:42:51 web.1    |   config.ru:5:in `require'                                                                                                        │
│ 23:42:51 web.1    |   config.ru:5:in `block in <main>'                                                                                                │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'                                                    │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'                                                       │
│ 23:42:51 web.1    |   config.ru:in `new'                                                                                                              │
│ 23:42:51 web.1    |   config.ru:in `<main>'                                                                                                           │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/rack-1.6.13/lib/rack/builder.rb:49:in `eval'                                                             │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/rack-1.6.13/lib/rack/builder.rb:49:in `new_from_string'                                                  │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/rack-1.6.13/lib/rack/builder.rb:40:in `parse_file'                                                       │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'                                               │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'                                                       │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'                                                    │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/lib/puma/cluster.rb:410:in `run'                                                             │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'                                                            │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'                                                                  │
│ 23:42:51 web.1    |   /usr/local/bundle/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'                                                            │
│ 23:42:51 web.1    |   /usr/local/bundle/bin/puma:23:in `load'                                                                                         │
│ 23:42:51 web.1    |   /usr/local/bundle/bin/puma:23:in `<top (required)>'                                                                             │
│ 23:42:51 web.1    | exited with code 1                                                                                                                │
│ 23:42:51 system   | sending SIGTERM to all processes                                                                                                  │
│ 23:42:51 worker.1 | exited with code 1  

I am new to Ruby, so I'd like to ask if you have some idea about what caused the crash.
Thanks!

**Comment by epugh** [comment]
I paired with @LiuCao0614 on this, and we resolved it.   Closing now!
