### ISSUE TITLE
Enable TLS for Redis 6 on Sidekiq on Heroku

### ISSUE THREAD

**Issue by michaelcizmar** [o19s/quepid#271]
**Describe the bug**
As described in this [stackoverflow](https://stackoverflow.com/questions/65834575/how-to-enable-tls-for-redis-6-on-sidekiq), TLS encryption is required on Redis 6 and thus you are unable to connect
From the article:

>  Redis 6 requires TLS to connect. However, Heroku support explained that they manage requests from the router level to the application level involving Self Signed Certs. Turns out, Heroku terminates SSL at the router level and requests are forwarded from there to the application via HTTP while everything is behind Heroku's Firewall and security measures

Since the application only configures sidekick via REDIS_URL, you need to update with variable.  (ideally it should read from REDIS_TLS_URL not since Heroku will update this variable automatically)

**To Reproduce**
1. Deploy app to heroku
2. Update your environment variable to the TLS endpoint
3. Attempt access jobs

**Expected behavior**
No error

**Candidate Code Change**
The following changes are suggested:
1) Utilize REDIS_TLS_URL conditionally
2) Conditionally via an environmental variable choose to not verify the redis ssl

`Sidekiq::Extensions.enable_delay!

sidekiq_config = { url: ENV['REDIS_URL'],
                   ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
                 }

Sidekiq.configure_server do |config|
  config.redis = sidekiq_config
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_config
end`

**Comment by epugh** [comment]
@michaelcizmar do you want to submit a PR for this?  I'd love to see this.
