### ISSUE TITLE
Expand/Collapse UI Hang

### ISSUE THREAD

**Issue by worleydl** [o19s/quepid#272]
**Describe the bug**
When expanding/collapsing queries on a larger case the UI can become completely locked in Chrome forcing the user to close out the tab.

**To Reproduce**
1. Create a large case
2. Click to expand/collapse queries and use the main paging to navigate around the case until the lock is triggered.

__Note__: Still trying to repro this locally, we did confirm the issue was happening with Liu tho.

**Expected behavior**
User should be able to click around all they want with no lockups

**Screenshots**

**Additional context**

**Comment by epugh** [comment]
I actually want to keep this ticket open, as the workaround isn't how we want to do this!   Hoping we get a real fix!

**Comment by matteomallus** [comment]
Hi @epugh, could you tell me if this issue was resolved or do we still need to set `QUERY_LIST_SORTABLE=true` to prevent the user interface from hanging? I'm also experiencing it on Firefox on Quepid 6.5.5

**Comment by epugh** [comment]
Nothing has been done explicitly to fix this problem, as it was very hard to debug...   Having said that, we are up to 6.14.0, so I'd love to hear if upgrading fixed it..   Lots and lots of good things!
