### ISSUE TITLE
Adding the possibility to send mails over SMTP

### ISSUE THREAD

**Issue by gabauer** [o19s/quepid#275]
|name           |about                                                            |title                                         |labels|assignees|
|---------------|-----------------------------------------------------------------|----------------------------------------------|------|---------|
|Feature request|Suggest to add the possibility to also use SMTP for sending mails|Adding the possibility to send mails over SMTP|      |         |
---

**Is your feature request related to a problem? Please describe.**

I want to host Quepid for a company for this it is necessary for me that the password reset button is working and can send mails over my own SMTP server. I want to add this functionality and extend the documentation.

**Describe the solution you'd like**

Because I'm new to ruby and rails, I don't know if this is the best solution, but I wanted to add a `smtp_mail_provider.rb` to the initializers folder where if a env var (`MAIL_METHOD`) is present and equals "smtp" the `Rails.application.config.action_mailer.delivery_method` is set to SMTP and the server details are read from the following env vars:

- SMTP_HOST
- SMTP_PORT
- SMTP_USERNAME
- SMTP_PASSWORD
- SMTP_AUTHENTICATION_TYPE
- SMTP_ENABLE_STARTTL

**Describe alternatives you've considered**

An alternative would be to place the code which sets action_mailer.delivery_method to SMTP in the `application.rb` or in an environment file under `environments/`.

- I decided not to use the environment files for this because the code would need to be repeated for test, development, staging, and production.
- I decided not to use the config/application.rb, because I think there should be only defined the standard delivery_method (postmark)

**Additional context**

If it is okay, I would like to take over this ticket.

**Comment by epugh** [comment]
I'd love to see this!   Thanks for sharing your thinking in the issue, this is a nicely written up example!

I think your approach of an initializer makes sense, and setting values based on my reading of https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration.

I expected to find our mailers in `/app/mailers`, and didn't, which reminded me that we use Devise for user auth, and those emails are sent by Devise.   Not sure that matters for waht you are trying!

**Comment by gabauer** [comment]
Thanks for the fast reply! I did the changes regarding this ticket in a local branch, but I can't push the branch to GitHub so that I can open a pull request.

@epugh can you help me with the process of getting permissions to do that?

**Comment by gabauer** [comment]
@epugh please ignore my stupid question. I found out that the normal process is forking and then opening an pull request. Will do this today.

**Comment by epugh** [comment]
There are no stupid questions!   I am super excited about your PR.
