### ISSUE TITLE
Unbounded query length

### ISSUE THREAD

**Issue by brigaldies** [o19s/quepid#277]
**Problem Statement**

The nature and content of the "q" parameter (i.e., the "query") can vary considerably from application to application. Usually, the q parameter simply contains the end-user's query, which is typically short, although some end-user's queries can be large too (i.e., several lines as in the use case of an end-user searching for an entire paragraph).

In more elaborate cases, the q parameter may contain a string representation of more complex concepts to be processed by a custom query parser, such as a custom parse tree that supports a custom query syntax, some kind of vector input, or in the case of a reverse search (Document-to-Queries matching) an entire document.

As of now, Quepid's underlying database column width for queries is 2000 characters, which limits Quepid's applicability as described above.

**Suggested Solutions**

1. Quepid shall allow unbounded queries' length by using the mySQL TEXT datatype.
2. On the UI:
  2.1 For screen real estate management, truncate the q text to the first N characters (e.g., N=40), and "..." at the end if the query was truncated.
  2.2 The end-user shall be able to click on the query in order to bring the entire query's text into view (popup, iframe, implementation TBD).

**Possible Issues**

Some TBDs:
- Changing the q column data type to TEXT might impact indexing and querying the q column, hence possibly affecting performance.
- Escaping, or not, of custom query text.

**Comment by gabauer** [comment]
@brigaldies I think I faced the same issue yesterday! :)
You are talking about the "query_text" column in the queries table right? How did you get the size of 2000 characters? For me, the column has a size of 191 characters.
I'd love to see this fixed and I also like your suggested solution. Do you like to fix this or can I open a pull request for it?

@epugh what's your opinion? What should be the maximum size of this column? What was the initial reason for restricting it to 191 chars?

**Comment by epugh** [comment]
There *really* wasn't a reason....   When it was first created, we were primarily using end user queries, which are typically shorter in nature.    During our _Quick Qlass on Quepid Qoding_ we'll use this issue to learn about coding against Quepid...   @gabauer I think I shared details on the class next wenesday with you?

**Comment by brigaldies** [comment]
Regarding the "2000" number for the current query text column width, I must have mis-heard Eric when we talked about the issue. Perhaps 2000 was the proposed new width. My suggestion to Eric was instead to make the query text unbounded so that it can contain any arbitrary text.

**Comment by gabauer** [comment]
@epugh thanks for the reply and the informations, unfortunately I don't have any information about a class next Wednesday but I'm looking forward to get some :)

**Comment by brigaldies** [comment]
Another thought on this issue is that an even better solution, for me, would be for Quepid to capture two things for any query:
1. The query's "display name", to be displayed on the UI. Typically, I would expect to see the end-user's typed text here.
2. The value of the "q" parameter (I'm talking Solr here, but this would also apply to ES), which may or may not be the same.

**Comment by epugh** [comment]
@gabauer  https://twitter.com/quepid_search/status/1362834690248441862
