### ISSUE TITLE
Soft-deletion feature leads to orphan snapshots

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#298]
**Describe the bug**
Managed to create an orphan snapshot with an equal name: Baseline.
One of these snapshots fetches correctly, the other one breaks the snapshot comparison dialogue box.

**To Reproduce**
Steps to reproduce the behavior (not a reliable way, because this bug is transient):
1. Create one snapshot with name "Baseline". It fails (for some reason, like connection to db)
2. Create second snapshot "Baseline". 
3. Try to load one snapshot, then the other. One of them fails to load.

**Expected behavior**
One snapshot gets created and it is valid.

**Additional context**
In the db, I queried with
```
select * from queries where case_id = 4
```
and got:

```
id	arranged_next	arranged_at	deleted	query_text	notes	threshold	threshold_enbl	case_id	scorer_id	scorer_enbl	created_at	updated_at	options
31	NULL	NULL	1	The Martian	NULL	NULL	NULL	4	NULL	NULL	2021-03-09 19:01:27	2021-03-12 09:46:53	NULL
33	NULL	NULL	1	Home Alone	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 09:46:32	2021-03-12 09:46:41	NULL
34	NULL	NULL	1	the martian	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 10:12:46	2021-03-12 10:12:52	NULL
35	6148914691236517204	3074457345618258602	NULL	The Martian	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 10:36:44	2021-03-12 10:52:17	NULL
36	NULL	NULL	1	Lion Kings	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 10:36:44	2021-03-12 10:36:50	NULL
37	9223372036854775807	6148914691236517204	NULL	Matrix	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 10:36:44	2021-03-12 10:52:17	NULL
38	3074457345618258602	1537228672809129301	NULL	Lion King	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 10:36:57	2021-03-12 10:52:35	NULL
39	NULL	NULL	1	Tiger King	NULL	NULL	NULL	4	NULL	NULL	2021-03-12 10:52:17	2021-03-12 10:52:26	NULL
40	1537228672809129301	0	NULL	Spaceballs	NULL	8	1	4	NULL	NULL	2021-03-12 10:52:34	2021-03-18 18:55:47	NULL
```

As you can see queries with ids 31 and 34 have deleted = 1 (soft-delete), and id=35 has deleted=NULL.
It could well be, that this soft-delete feature leads to case inconsistency.

**Screenshots**
![image](https://user-images.githubusercontent.com/123553/111985317-210ce780-8b15-11eb-92df-1145280651c6.png)

08:08:08 web.1    | Started GET "/api/cases/4/snapshots/4" for 172.18.0.1 at 2021-03-13 08:08:08 +0000
08:08:08 web.1    | Processing by Api::V1::SnapshotsController#show as JSON
08:08:08 web.1    |   Parameters: {"case_id"=>"4", "id"=>"4"}
08:08:08 web.1    |   User Exists (0.6ms)  SELECT  1 AS one FROM `users` LEFT OUTER JOIN `permissions` ON `permissions`.`user_id` = `users`.`id` WHERE `users`.`id` = 1 LIMIT 1
08:08:08 web.1    |   User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
08:08:08 web.1    |   Permission Load (0.8ms)  SELECT `permissions`.* FROM `permissions` WHERE `permissions`.`user_id` IN (1)
08:08:08 web.1    |   SQL (1.5ms)  SELECT  DISTINCT `cases`.`id`, `cases`.`id` AS alias_0 FROM `cases` LEFT OUTER JOIN `case_metadata` ON `case_metadata`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams_cases` ON `teams_cases`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams` ON `teams`.`id` = `teams_cases`.`team_id` LEFT OUTER JOIN `teams_members` ON `teams_members`.`team_id` = `teams`.`id` LEFT OUTER JOIN `users` ON `users`.`id` = `teams_members`.`member_id` WHERE ((`teams`.`owner_id` = 1 OR `teams_members`.`member_id` = 1) OR `cases`.`user_id` = 1) AND `cases`.`id` = 4  ORDER BY `cases`.`id` ASC LIMIT 1
08:08:08 web.1    |   SQL (1.6ms)  SELECT `cases`.`id` AS t0_r0, `cases`.`case_name` AS t0_r1, `cases`.`last_try_number` AS t0_r2, `cases`.`user_id` AS t0_r3, `cases`.`archived` AS t0_r4, `cases`.`scorer_id` AS t0_r5, `cases`.`created_at` AS t0_r6, `cases`.`updated_at` AS t0_r7, `case_metadata`.`id` AS t1_r0, `case_metadata`.`user_id` AS t1_r1, `case_metadata`.`case_id` AS t1_r2, `case_metadata`.`last_viewed_at` AS t1_r3, `teams`.`id` AS t2_r0, `teams`.`name` AS t2_r1, `teams`.`owner_id` AS t2_r2, `teams`.`created_at` AS t2_r3, `teams`.`updated_at` AS t2_r4, `users`.`id` AS t3_r0, `users`.`email` AS t3_r1, `users`.`password` AS t3_r2, `users`.`agreed_time` AS t3_r3, `users`.`agreed` AS t3_r4, `users`.`first_login` AS t3_r5, `users`.`num_logins` AS t3_r6, `users`.`name` AS t3_r7, `users`.`administrator` AS t3_r8, `users`.`reset_password_token` AS t3_r9, `users`.`reset_password_sent_at` AS t3_r10, `users`.`company` AS t3_r11, `users`.`locked` AS t3_r12, `users`.`locked_at` AS t3_r13, `users`.`created_at` AS t3_r14, `users`.`updated_at` AS t3_r15, `users`.`default_scorer_id` AS t3_r16, `users`.`email_marketing` AS t3_r17 FROM `cases` LEFT OUTER JOIN `case_metadata` ON `case_metadata`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams_cases` ON `teams_cases`.`case_id` = `cases`.`id` LEFT OUTER JOIN `teams` ON `teams`.`id` = `teams_cases`.`team_id` LEFT OUTER JOIN `teams_members` ON `teams_members`.`team_id` = `teams`.`id` LEFT OUTER JOIN `users` ON `users`.`id` = `teams_members`.`member_id` WHERE ((`teams`.`owner_id` = 1 OR `teams_members`.`member_id` = 1) OR `cases`.`user_id` = 1) AND `cases`.`id` = 4 AND `cases`.`id` IN (4)  ORDER BY `cases`.`id` ASC
08:08:08 web.1    |   Snapshot Load (0.7ms)  SELECT  `snapshots`.* FROM `snapshots` WHERE `snapshots`.`case_id` = 4 AND `snapshots`.`id` = 4  ORDER BY `snapshots`.`id` ASC LIMIT 1
08:08:08 web.1    |   SnapshotQuery Load (0.4ms)  SELECT `snapshot_queries`.* FROM `snapshot_queries` WHERE `snapshot_queries`.`snapshot_id` IN (4)
08:08:08 web.1    |   SnapshotDoc Load (0.7ms)  SELECT `snapshot_docs`.* FROM `snapshot_docs` WHERE `snapshot_docs`.`snapshot_query_id` IN (18)  ORDER BY `snapshot_docs`.`position` ASC
08:08:08 web.1    |   Query Load (1.2ms)  SELECT  `queries`.* FROM `queries` WHERE (`queries`.`deleted` = 0 OR `queries`.`deleted` IS NULL) AND `queries`.`id` = 31 LIMIT 1
08:08:08 web.1    |   Rendered api/v1/queries/_query.json.jbuilder (2.0ms)
08:08:08 web.1    |   Rendered api/v1/snapshots/_snapshot.json.jbuilder (11.4ms)
08:08:08 web.1    |   Rendered api/v1/snapshots/show.json.jbuilder (13.3ms)
08:08:08 web.1    | Completed 500 Internal Server Error in 173ms (ActiveRecord: 28.9ms)
08:08:08 web.1    | 
08:08:08 web.1    | ActionView::Template::Error (undefined method `arranged_at' for nil:NilClass):
08:08:08 web.1    |     1: # frozen_string_literal: true
08:08:08 web.1    |     2: 
08:08:08 web.1    |     3: json.arrangedAt         query.arranged_at
08:08:08 web.1    |     4: json.arrangedNext       query.arranged_next
08:08:08 web.1    |     5: json.deleted            query.deleted
08:08:08 web.1    |     6: json.queryId            query.id
08:08:08 web.1    |   app/views/api/v1/queries/_query.json.jbuilder:3:in `_app_views_api_v__queries__query_json_jbuilder___893051533646138441_46979855083640'
08:08:08 web.1    |   app/views/api/v1/snapshots/_snapshot.json.jbuilder:21:in `block in _app_views_api_v__snapshots__snapshot_json_jbuilder__2683437120897967833_70054272691120'
08:08:08 web.1    |   app/views/api/v1/snapshots/_snapshot.json.jbuilder:20:in `_app_views_api_v__snapshots__snapshot_json_jbuilder__2683437120897967833_70054272691120'
08:08:08 web.1    |   app/views/api/v1/snapshots/show.json.jbuilder:3:in `_app_views_api_v__snapshots_show_json_jbuilder__1280429872279868987_46979855154620'
08:08:08 web.1    |   app/controllers/api/v1/snapshots_controller.rb:38:in `show'
08:08:08 web.1    | 
08:08:08 web.1    |

**Comment by epugh** [comment]
I have confirmed that dekleting a query deletes out of the snapshotted version too, which is what I would expect...

**Comment by DmitryKey** [comment]
great! Less reason for the DB inconsistencies => more stable code.
