### ISSUE TITLE
Add rating level notes

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#301]
**Is your feature request related to a problem? Please describe.**
A need came up: leave notes on specific rating. Of course, another way is to not implement this feature and foster better communication! Which I like as well actually.

My use case today was, asking a rater: why did you give this document a 0, and this one (almost similar) — a 2? (0-3 scale). He said: oh, I made a mistake, I will fix it.
And for other less straightforward cases he had to explain over a call. I think that if I have a team of  10 raters, I will need per-rating commenting feature to follow up.

**Describe the solution you'd like**
Per rating comments. UX needs some good thought, but can be as simple as some visual clue (*) on the rating, like:

      [4(*)]    doc_title

when clicking on the rating you'd get a comment in a tooltip or a resizable comment overlay window.

**Describe alternatives you've considered**
Calling raters. Sometimes it is ok, but for larger team going to be harder.

**Comment by DmitryKey** [comment]
Quick mockup:
https://dima814108.invisionapp.com/console/share/DX2DRRG0B4/576022274

**Comment by epugh** [comment]
I was mulling over a similar idea...    I'd like to have an explicit "Info Need" statement per query.   Historically I've tossed this in as a "NOtes", but I think it's pretty common pattern to have a written info need per query, and so maybe we add a new field to the `query` table ;-)(.       

In Rails 6 we have ActionText: https://edgeguides.rubyonrails.org/action_text_overview.html:

> Action Text brings rich text content and editing to Rails. It includes the Trix editor that handles everything from formatting to links to quotes to lists to embedded images and galleries. The rich text content generated by the Trix editor is saved in its own RichText model that's associated with any existing Active Record model in the application. Any embedded images (or other attachments) are automatically stored using Active Storage and associated with the included RichText model.

I think this would be a great feature to add post Rails 6 upgrade ;-)

**Comment by epugh** [comment]
Maybe on our next Quepid Qoding session we could workshop this idea, and maybe where else we would want more tracking/details?

**Comment by DmitryKey** [comment]
@epugh and I have iterated on this idea further, recording and details will follow in this ticket.

**Comment by epugh** [comment]
@DmitryKey  do you have the recording for this?     

I just ran into a situation where I need to load 250 queries from a spreadsheet, and I want to bring in the "intent", and I can't ;-(.  We really need a "query.intent" field to track that information!   Or just a better way to bring in Notes.
