### ISSUE TITLE
Tracking Last Scores is Broken

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#306]
**Describe the bug**
We are not actually sending the scorers since 2021-03-05 15:03:03 in app.quepid.com!   That was the last time the table `cases_scores` had an update.

Thanks @dmitrykey for finding this while testing #303 

**To Reproduce**
1. Go to any case
2. run the scorer
3. check the database table `case_scorers` and you won't see a record.

I believe this is on the front end, we see:

```
$log.info('sending score information to mothership');
caseSvc.trackLastScore(caseNo, lastScoreTracker);
```

But nothing ever happens!

Inside of `trackLastScore` we have this method that i think is the issue:

```
        if (  angular.isUndefined(scoreData.queries) ||
              scoreData.queries === null ||
              Object.keys(scoreData.queries).length === 0
        ) {
          return $q(function(resolve) {
            resolve();
          });
        }
```

We never finish and move to the next line where we actually send the data to the API!

**Expected behavior**
records in `case_scorers`

**Screenshots**
See the screenshots on #303 

**Additional context**
This is a critical bug to fix, yet it's been there for three weeks.  Sigh.   Going to pair with @worleydl on it on Monday.

**Comment by DmitryKey** [comment]
Is there a way to unit-test this?

**Comment by epugh** [comment]
> Is there a way to unit-test this?

Just to follow up on your question, while we have great unit testing on front end and backend individually, we don't have any integration testing that crosses these boundaries.      We also don't have a ton of integration testing in the frontend between how the app works and how the services respond...   We could write them I suppose.   I sort of assume that the app will break visibily, though in this case it took a long time. 

We shoudl add some better integration tests...

**Comment by DmitryKey** [comment]
I hope to contribute some integration tests.. I think this is good way to start with coding something up!
