### ISSUE TITLE
Add sort queries by modification date

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#307]
**Is your feature request related to a problem? Please describe.**
Sort queries by modification time. Can be very useful when there are several screens of queries and you need only portion that has been annotated / rated.

**Describe the solution you'd like**
Add "modification date" to:
<img width="274" alt="Screenshot 2021-03-29 at 22 22 00" src="https://user-images.githubusercontent.com/123553/112888579-32d62800-90dd-11eb-9585-d709b20b29d7.png">

**Describe alternatives you've considered**
Manual drag and drop of queries, but this does not work for multipage situation (I have 65 queries in a single case).

**Comment by DmitryKey** [comment]
hey @epugh I'm thinking to work on this one. I will start by tracing the code for the current sort fields and see where this leads to.

**Comment by epugh** [comment]
Great...     I believe this all happens in the front end angular code...   And there are some exampples to copy.   I tend to use lots of `console.log();` to figure things out, and lots of refreshing the browser ;-)    

During next Friday's Quepid Qommunity Qoding session I can pair with you as well.

**Comment by DmitryKey** [comment]
Thanks and that'd be awesome to pair on this. 
I'm looking at https://itnext.io/debugging-your-angular-application-in-intellij-idea-411a9b08759f as one possible way to ease the process with IDEA.

**Comment by DmitryKey** [comment]
Fix implemented by Eric in a pair-programming session, including some commits from here

**Comment by DmitryKey** [comment]
@epugh will you reopen this? :)

**Comment by epugh** [comment]
Odd, I thought any comments would reopen an issue!

**Comment by DmitryKey** [comment]
yep! Well, at least the stale bot has automagically removed the "wontfix" label!

**Comment by epugh** [comment]
Okay, it's merged, so going to close this!   Release soon!
