### ISSUE TITLE
Research webpack (and possibly integrate it)

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#318]
Research webpack integration: https://www.freecodecamp.org/news/how-to-configure-webpack-4-with-angular-7-a-complete-guide-9a23c879f471/

Also see this for debugging in Intellij IDEA: https://itnext.io/debugging-your-angular-application-in-intellij-idea-411a9b08759f

Precaution: this is completely unchartered waters for me!

**Comment by DmitryKey** [comment]
https://github.com/rails/rails/pull/33079

@epugh what do you think of upgrading to Rails 6?

**Comment by epugh** [comment]
I think this is definitly the pre-requisite...    Otherwise we are creating a lot of our own tooling.     So @ychaker feel like joining on a Quepid Qommunity Qoding hour some time to get us started?

**Comment by DmitryKey** [comment]
Cool! I've played with a sample blogging app from rails/realities, it illustrates webpack, see video here: https://www.youtube.com/watch?v=HJZ9TnKrt7Q

Currently I'm looking at integrating this into quepid. First step done: in Gemfile:

    gem 'rails', '= 6.1.3.2' # starting Rails 6 the webpack is included by default.
    gem 'webpacker', '= 5.4.0'

**Comment by DmitryKey** [comment]
It runs, however force_ssl method isn't reachable (probably dropped from Rails 6), so I had to comment it out for now. Otherwise UI loads, I can create cases.

**Comment by epugh** [comment]
Wow!!!!!!!!!!!!!!!!!!!!!!!!!!!

So, this is a useful tool for diffing default Rails apps, I used it to get to 5.2 from Rails 4.   

https://railsdiff.org/5.2.4.6/6.1.3.1


This is pretty amazing that you did get this far so quickly!   I was kind of dreading it, thinking it was going to be as hard as the initial jump to Rails 5, but this makes me think this might be easy?

**Comment by DmitryKey** [comment]
@epugh I've opened the PR ^. But! I need more wizard help from you or anybody who understands docker/rails/angular world.
The thing is, that in the demo blog app Webpacker got configured correctly. And for that I used rails/realties.

In the PR I've generated webpack config files using:

```bash
bin/rails webpacker:install
```

I've also disabled app preloading for now, assuming this stuff will be handled by webpack.
Also added new section ### Webpacker to the README.md.

If you have time, give it a spin.

**Comment by DmitryKey** [comment]
Btw, thanks for the diff link, it looks really useful. We can upgrade Puma for instance.

Stashing a few relevant links:
https://github.com/preboot/angularjs-webpack/blob/master/webpack.config.js angular + webpack
https://www.nopio.com/blog/angularjs-rubyonrails-tutorial/ -- good tutorial for angularjs with RoR

https://medium.com/@zamarrowski/angular-1-x-component-based-application-with-webpack-and-es6-dfab450f2df4 a bit dated tutorial for webpack and angular, but might be still relevant.

**Comment by DmitryKey** [comment]
Update: we have upgraded Quepid to Rails 6, which supports webpack out of the box. But we need Frontend developer wizardry to help us roll out webpack.
The impact of using webpack is speeding up the UI development. Currently it takes 30 seconds to reflect a change in the frontend code, which is annoying.
If you are a frontend engineer and would like learn / contribute to open source, we have regular Community meetings online to brainstorm and do pair programming.

**Comment by epugh** [comment]
FYI, in Rails 7, there is a lot of work to remove the entire need for Node, and this may become OBE...

**Comment by DmitryKey** [comment]
yip-yip :))
