### ISSUE TITLE
Add OpenSearch as a search engine Quepid supports

### ISSUE THREAD

**Issue by flaxsearch** [o19s/quepid#319]
AWS OpenSearch is the new OSS fork of Elasticsearch. Can we add this as a third engine Quepid supports?

I'm guessing and hoping that as the APIs are currently identical we can just copy-and-paste a lot of code, and add a third radio button in the UI. I don't know the implications of this though! We'll also need to modify documentation and the website.

**Comment by epugh** [comment]
This ticket actually speaks to one of the big limitations of Quepid, which is it's tied to direct connections to Elasticsearch and Solr...    I have been playing with proxies, to convert "Your random search engine to look like Solr" or "Your random search api to look like Solr", and the approach works.    Longer term, however, we need to figure out how to transform a response to what Quepid needs internally.

I'm going to document the "What a Search Engine Needs to Provide" to work with Quepid, and see about building a direction...!

**Comment by DmitryKey** [comment]
Idea: include a mocked search engine with the API that complies with Quepid expected format directly into Quepid package.
Someone who wants to investigate this path will have not only the documentation, but also a real practical shiny simple not-solr, not-elasticsearch, not-opensearch search engine.

I'm willing to contribute a recommendation engine, that can be plugged into Quepid, because this can open the door to a very large community of ML/NLP folks.

Starting with documenting the vision as @epugh suggests is the first big step towards this goal.

**Comment by epugh** [comment]
So, I put in https://github.com/o19s/quepid/blob/master/docs/endpoints_solr.md as a starting point.

**Comment by flaxsearch** [comment]
Bumping this as OpenSearch is now GA.

**Comment by DmitryKey** [comment]
A progress update from my side: in my team we managed to plug in our own search API, that applies Query Understanding to the query and outputs a set of filters, which are then applied on the Elasticsearch query. The API returns Elasticsearch JSON shape back to Quepid, so Quepid thinks it is Elasticsearch, when it is not.

**Comment by flaxsearch** [comment]
Re-animating this one as it's something Eric mentioned recently

**Comment by epugh** [comment]
Maybe @jzonthemtn or @mkr will save us!

**Comment by epugh** [comment]
To make this happen, once we have updated `splainer-search` via `package.json`, and assuming we are doing a light weight implementation...

* https://github.com/o19s/quepid/blob/main/app/models/try.rb needs to know how to handle OpenSearch, this appears to be the only Rails side that needs changes.....


Search for 'es' in *.js files.   I would start with the services, make sure the tests STILL pass, then do the others:
* https://github.com/o19s/quepid/blob/main/app/assets/javascripts/controllers/docFinder.js#L191 needs updates
* https://github.com/o19s/quepid/blob/main/app/assets/javascripts/controllers/wizardModal.js#L28
* https://github.com/o19s/quepid/blob/main/app/assets/javascripts/controllers/queryParams.js#L25
* https://github.com/o19s/quepid/blob/main/app/assets/javascripts/services/queriesSvc.js#L102
* https://github.com/o19s/quepid/blob/main/app/assets/javascripts/services/settingsSvc.js#L43

Plus we need to update the UI.   Search for 'solr' in *.html
* devQueryParams.html
* queryDiffResults.html
* searchResults.html
* targetedSearchModal.html
* wizardModal.html

**Comment by epugh** [comment]
Fixed in #559 !!!!!!!!!!!!!!!!
