### ISSUE TITLE
Custom scorers not editable

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#321]
**Describe the bug**
I create a new custom scorer, and select a scale, e.g. Fibonacci. However, it is saved with an empty scale `"scale": []`, thus when you load it there is no scale, and the UI shows the radio button "Custom", with an empty text-box. Trying to add e.g `1,2,3,4,5` in that textbox will not save either, it always comes back as empty.

**To Reproduce**
1. Add a custom scorer
2. Select a scale, e.g. standard 1-10
3. Save
4. Reload page, the scorer comes back with "Custom" scale with emtpy box

**Expected behavior**
The app should remember the chosen scale

**Screenshots**
![Skjermbilde 2021-04-14 kl  11 39 14](https://user-images.githubusercontent.com/409128/114769604-b5601800-9d6a-11eb-87f0-a0ce384217e7.png)

**Additional context**
https://relevancy.slack.com/archives/CJ42JGQ6L/p1618393438057100

**Comment by epugh** [comment]
As usual, thank you for a very clear bug!

**Comment by epugh** [comment]
This is fun...  We think that scale is `scale:=>[1,2,3,4]`, ie an array, but it appears to be a string: `"scale"=>"1,2"` or even `"scale"=>"1, 2, 3, 4"`

**Comment by epugh** [comment]
ah ha!   on creates, i.e POST, its a string.   On updates, i.e PUT, its an array.   Of course.
