### ISSUE TITLE
"Show only rated" active skips matching docs

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#325]
**Describe the bug**
When using the "Show only rated" feature, the hit counts in main result is wrong, and the "Explain Missing" dialogue explains only top-10 of the rated docs. Then if you click "Peed at the next page of results", it will explain the first 10 of the next page.

**To Reproduce**
1. Define a case with a query with a high number of rated docs, say 60.
2. Toggle "Show only rated"
3. The result count in right margin is lower than actual number of rated docs
4. Click "Explain missing"
5. The dialogue shows correct number of rated docs (e.g. 60)
6. Scroll down to "Rank: #10". It has explaination of the matches
7. Scroll further down to "Rank: #11". It does not have explanation
8. Page to the next page of rated docs, and see the pattern repeat (only first 10 have explain)

**Expected behavior**
* See correct hit count in margin
* Explain missing is able to explain all the hits

**Screenshots**
In this example, we have a simple query "strømpriser" with 110 active ratings - all of them matches the query. 
![Skjermbilde 2021-04-21 kl  16 09 06](https://user-images.githubusercontent.com/409128/115570224-3c0e7b00-a2be-11eb-846b-754ff793c123.png)
But the UI says there are 50 results when "Show only rated" is toggled:
![Skjermbilde 2021-04-21 kl  16 09 16](https://user-images.githubusercontent.com/409128/115570246-3fa20200-a2be-11eb-9f0e-547e117b0099.png)
"Explain missing" shows correct number of rated docs
![Skjermbilde 2021-04-21 kl  16 09 37](https://user-images.githubusercontent.com/409128/115570266-43358900-a2be-11eb-95c4-0426677037c7.png)
...but it fails to explain hits no 11 and onwards.
![Skjermbilde 2021-04-21 kl  16 10 12](https://user-images.githubusercontent.com/409128/115570276-46c91000-a2be-11eb-8a87-ed0f380e89d4.png)

**Additional context**
N/A

**Comment by worleydl** [comment]
Thanks Jan.

For the incorrect count, is it being limited to 50 or does it vary per query?

**Comment by janhoy** [comment]
No, we have some queries with more than 100 judgements, and there the count is 99. But several queries suspiciously end up with 50 :)

**Comment by worleydl** [comment]
Bumpin to call off stalebot
