### ISSUE TITLE
Adding a result evaluation leasds to UI slowness and huge number of requests to the backend

### ISSUE THREAD

**Issue by thePanz** [o19s/quepid#330]
**Describe the bug**
Adding 1 evaluation triggers 300+ requests, and a huge delay in the UI

**To Reproduce**
1. Create a new relevance case with ES as search backend
2. Add 10 keywords (which leads to results)
3. Add evaluation grades to each result
4. Try to add another grade: it is not possible as the UI is frozen for few seconds
5. Check the Network tab of the browser: for each added grade, multiple requests (up to 300 in my case) are triggered to the backend and ES

**Expected behavior**
- Adding evaluations should trigger the minimum amount of requests to the backend
- some requests are the same (around 48 requests for 1 added grade) to /api/cases/1/scores/all
- if possible allow to manually refresh the "case's scores", and do not automatically trigger it after adding a single grade

**Screenshots**
The requests (327) are related to adding 1 grade (I cleaned the "network" tab before clicking on the grade)
![image](https://user-images.githubusercontent.com/226021/116427436-514a5300-a844-11eb-84e7-99917858eb86.png)

**Additional context**
- ES is my backend
- The search case has 25 searches/keywords
- Each search has from 10 to 250 results each

**Comment by epugh** [comment]
Thank you for this issue!   I had _felt_ like I was seeing really large number of queries in logs on the server side, and just a general sense of slowness.     I'd love some help tracking down when this issue might have been introduced....

**Comment by thePanz** [comment]
I had the same behavior with the latest 2 releases (I am using the official docker images)

**Comment by epugh** [comment]
can you confirm you saw the issue in 6.4.1 docker image?  Would you be willing to retest in 6.3.2?    I was assuming this was caused due to Rails 5 upgrade that happened in 6.5.0, but maybe it's been there for longer...    If it isn't in 6.3.2, then it was probably introduced by the work for the "Show Only Rated" toggle feature.....

**Comment by thePanz** [comment]
@epugh I can confirm that using the docker-image v6.3.2 (with the same DB), the UI does *NOT* have the slowdown issue.
The problem might have been introduced after v6.3.2

**Comment by thePanz** [comment]
@epugh any update on this issue? :)

**Comment by epugh** [comment]
Not really ;-(.    Would you be willing to schedule a short Zoom call to look at this issue together and make sure I can duplicate it?   https://calendly.com/epugh/30-minute-quepid-qonversation

**Comment by epugh** [comment]
Did you want to look at this again?  I'm prepping for the next release, so if there is an issue, now is a good bug swatting time to find this!

**Comment by epugh** [comment]
<img width="244" alt="image" src="https://user-images.githubusercontent.com/22395/133926959-2a9a4be1-c3f1-41cf-a297-5515c2fc0ecf.png">

I am seeing this ;-(    One query, and a BUNCH of calls...

**Comment by thePanz** [comment]
@epugh unfortunately I am not using this tool anymore, but ""happy"" to hear that you've been able to reproduce the issue :)

**Comment by epugh** [comment]
Ugh, found it again!

**Comment by epugh** [comment]
@worleydl ping!
