### ISSUE TITLE
URL detection treats any occurance of http as a url

### ISSUE THREAD

**Issue by pfries** [o19s/quepid#34]
**Describe the bug**

The new auto-URL feature introduced here https://github.com/o19s/quepid/pull/27 will wrap any string containing the substring "http" anywhere in the string.

**To Reproduce**
1. Add a display field for a document that has http in the value but not a url.
2. Check the display and the entire value is hyperlinked.

**Expected behavior**
Only strings beginning with http should be hyperlinked.

**Comment by epugh** [comment]
And fixed!
