### ISSUE TITLE
Basic CSV export includes too many LFs at the end of the file

### ISSUE THREAD

**Issue by sstults** [o19s/quepid#354]
**Describe the bug**
The Exporter includes blank lines at the end of the file. This causes problems with feeding judgements into Quaerite. Removing the blank line manually fixes the problem. The class that reads the CSV is `org.apache.commons.csv.CSVRecord`

**To Reproduce**
1. Go to a case
2. Click on Export
3. Scroll down to Basic and select it
4. Click Export
5. Inspect the resulting file and see the extra blank line

**Expected behavior**
The CSV should terminate with a single blank line.

**Comment by epugh** [comment]
This is totally a Quaerite issue in not being robust and they should fix it!

**Comment by epugh** [comment]
Let's pair on this, as the issue must be in https://github.com/o19s/quepid/blob/master/app/views/api/v1/export/ratings/show.basic.csv.erb
