### ISSUE TITLE
Basic Export creates invalid CSVs when no ratings exist

### ISSUE THREAD

**Issue by sstults** [o19s/quepid#364]
**Describe the bug**
CSV readers throw an error when the header line specifies a number of columns but all records do not have that number of columns.

**To Reproduce**
1. Go to a Case where some queries have not been rated
2. Click on Export
3. Scroll down to Basic
4. Click Export
5. Examine the CSV: Entries that have no ratings do not supply the correct number of commas (2)

**Expected behavior**
If a query doesn't have ratings it should either be skipped altogether or empty columns added. For example, a query for "foo" would look like this:

```bash
query,docid,rating
foo,,
```

The way it works now is:
```
query,docid,rating
foo
```

**Screenshots**

**Additional context**

**Comment by epugh** [comment]
Hey @sstults what about

```
query,docid,rating
two, , 
```

**Comment by epugh** [comment]
Never mind, I got it to:

```
query,docid,rating
foo,, 

```
