### ISSUE TITLE
Variable ("knobs") values should be copied with clone

### ISSUE THREAD

**Issue by peterdm** [o19s/quepid#37]
**Describe the bug**
The names of any custom variables are copied with "clone", but the values are not.

**To Reproduce**
1. Create a case
2. Create a test query with a variable token:  (E.g. "q=id:##the_id_is_always_43##")
3. Click on the "variables" and confirm that there is a field for "the_id_is_always_43"
4. Set "the_id_is_always_43" to be 43.
5. Rerun the query and confirm that it's using the variable.
6. NOW... clone the case
7.  In the clone, examine the "variables" and ensure that "the_id_is_always_43" equals 43.
8. If not, you have reproduced the bug.

**Expected behavior**
Variable values would be cloned with the case.

**Screenshots**

**Additional context**

**Comment by epugh** [comment]
Thank you...

**Comment by epugh** [comment]
Argh, I tried it out with localhost version of quepid, and the variable copied over just fine.   Going to try with online version.

**Comment by epugh** [comment]
okay, with the online version, I lost the variable value that had been set, it went back to the default 10, however the variable was still there.   So this seems reproducible.

**Comment by epugh** [comment]
Okay, a couple of things that I've found.   table `curator_variables` stores the value of the variable.   When we clone the case, we don't actually clone the records in `curator_variables`.   Also annoying is the fk to table `tries` is called `query_param_id` and NOT called `try_id`.

**Comment by epugh** [comment]
okay, made a lot of progress..   going to let me branch sit for a day (it's late!) and then merge.
