### ISSUE TITLE
"Snapshot" score does not update when switching comparative snapshots

### ISSUE THREAD

**Issue by peterdm** [o19s/quepid#387]
**Describe the bug**
When comparing snapshots, the "snapshot score" is only calculated for the initial snapshot selected when the comparison view loads.

Any subsequent snapshots selected without first `Disable`-ing the "Compare Snapshots" mode will retain the original score from the first snapshot chosen.

**To Reproduce**
1. Given: 2 snapshots saved (Snap 1, Snap 2) with score difference.
2. Compare each snapshot individually with the current state ("Disable" comparison in between).
3. Note the individual scores of each snapshot.
4. Now reactivate the comparison using Snap 1 (verify that the score is the same as just noted).
5. WITHOUT first selecting "Disable" from the "Compare Snapshot" popup, select Snap 2.
6. You should see the error reproduced:  the Snap 1 score will remain in the top green box even though Snap 2 data has loaded.

**Expected behavior**
Should be able to switch between snapshots and have the snapshot score update correctly at the time of the switch.

**Comment by epugh** [comment]
Looking now.

**Comment by epugh** [comment]
Here is comparison 1:
![snapshot_1_comp](https://user-images.githubusercontent.com/22395/128513729-83c5ce32-cc63-4277-8ba0-69eae7bb7cc0.png)

Here is comparison 2:
![snapshot_2_comp](https://user-images.githubusercontent.com/22395/128513734-234822c2-852b-4946-8bd9-5f83b774b271.png)

Here is going from comparison 1 to comparison 2 without a "Disable" in between demonstrating the problem.
![comp_snap1_to_snap2](https://user-images.githubusercontent.com/22395/128513742-e96bc34d-9677-4d32-bec8-93afd0ec807f.png)

**Comment by epugh** [comment]
@worleydl I think I need you magic...  I've tried to fix it with no luck.  Totally duplicatable, but my understanding of eventing, and how to listen to the change in diff choice is just not there.   Could you take a look?
