### ISSUE TITLE
Comparing of snapshots doesn't work with russian letters

### ISSUE THREAD

**Issue by chadiman43** [o19s/quepid#4]
**Describe the bug**
"Comparing of snapshots doesn't work, if one of the queries in Relevancy cases contains russian letters "

**To Reproduce**
1. Go to 'Relevancy cases'
2. Create any snapshot
3. Add query with russian letters. 'обои', for example
3. Go to 'Compare snapshot'
4. Choose your snapshot
5. See empty results on the screen at the right side

**Expected behavior**
If all queries doesn't contain russian letters, everything works as well, we can look at old and new search results.

**Screenshots**
![screen2](https://user-images.githubusercontent.com/48061710/63756447-0f277c00-c8c1-11e9-896a-a9196bca12d4.jpg)
![screen1](https://user-images.githubusercontent.com/48061710/63756448-0f277c00-c8c1-11e9-8ac5-6e64398fbd2a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 75.0.3770.142

**Comment by epugh** [comment]
@chadiman43 I found some time to look at your ticket (sorry it's taken so long!)...    I *think* you are on Elasticsearch, judging from the screenshots.   I know Solr better, so I made a quick index:

Create collection
```
curl "http://quepid-solr.dev.o19s.com:8985/solr/admin/collections?action=CREATE&name=test_issue_4&numShards=1&replicationFactor=1&wt=xml&collection.configName=tmdb"
```

Index two docs, one in Russian
```
curl -X POST -H 'Content-Type: application/json' 'http://quepid-solr.dev.o19s.com:8985/solr/test_issue_4/update/json/docs?commit=true' --data-binary '
[
  {
    "id": "1",
    "title": "English Doc"
  },
  {
    "id": "1",
    "title": "Russian обои"
  },  
]'
```

This search blows up with a Jetty error
```
curl "http://quepid-solr.dev.o19s.com:8985/solr/test_issue_4/select?q=title:обои"
```
This one works!
```
curl http://quepid-solr.dev.o19s.com:8985/solr/test_issue_4/query -d 'json={"query":"обои"}'
```

**Comment by epugh** [comment]
Okay, went ahead and mocked up a ES server:



### Create ES Index

```
curl -X PUT "http://quepid-elasticsearch.dev.o19s.com:9207/quepid_issue_4?pretty" -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "properties" : {
            "field1" : { "type" : "text" }
        }
    }
}
'
```

### Insert docs

```
curl -X POST "http://quepid-elasticsearch.dev.o19s.com:9207/quepid_issue_4/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
    "field1" : "english doc"
}
'
```

```
curl -X POST "http://quepid-elasticsearch.dev.o19s.com:9207/quepid_issue_4/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
    "field1" : "Russian обои"
}
'
```

### search

```
curl -X GET "http://quepid-elasticsearch.dev.o19s.com:9207/quepid_issue_4/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "term" : { "field1" : "english" }
    }
}
'

```

```
curl -X GET "http://quepid-elasticsearch.dev.o19s.com:9207/quepid_issue_4/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "term" : { "field1" : "обои" }
    }
}
'

```

**Comment by epugh** [comment]
Okay, tested Quepid out locally, and the snapshot seemed to work with the Russian language query **обои**.

See this screenshot:
<img width="696" alt="snapshot" src="https://user-images.githubusercontent.com/22395/69503778-60a8cc80-0eeb-11ea-8cd5-7689f3beb346.png">

**Comment by epugh** [comment]
Let me know if you run into any other problems, and please reopen this issue!
