### ISSUE TITLE
Search box and filters against list of queries

### ISSUE THREAD

**Issue by danielibars** [o19s/quepid#403]
When you have a lot of query cases on Quepid, it gets very difficult to navigate through them if you don't have the right tools to filter or search for a particular query.

I used Quepid on a case with more than 15 pages. It is hard to navigate and find a particular query or a group of queries with similar conditions.

A search box and or a filter toolbox will help a lot!!

**Comment by danielibars** [comment]
- The filter toolbox should allow to filter in/out against the frog (show/hide rated/unrated queries)
- The search box should help filter queries by combination of characters
-  Filter by a keyword field on the documents
Any other idea is wellcome!!

**Comment by epugh** [comment]
I did some looking, and we could use the same Angular 1 filter widget that we apply on the case Listing and the Team Listing page!
