### ISSUE TITLE
Create health check route

### ISSUE THREAD

**Issue by mkr** [o19s/quepid#405]
**Is your feature request related to a problem? Please describe.**
Automated service health checks (with monitors and possibly service restarts upon failure) are best practice in environments such as Kubernetes or AWS EC2. It would be great if Quepid could expose a dedicated HTTP endpoint that indicates Quepid's readiness to accept end user HTTP requests.

**Describe the solution you'd like**
An HTTP endpoint such as `/health` that responds with 200 OK and possible a small JSON snippet version of the Quepid version or 50x (or refuse connection which a proxy will propagate as 502 Bad Gateway) if the Quepid routes are not ready yet.

**Describe alternatives you've considered**
Performing health-checks on any other (internal) route currently exposed by Quepid (such as /sessions etc.) incurs the risk of health checks failing if these internal routes change.

**Comment by epugh** [comment]
Done!
