### ISSUE TITLE
Provide backlinks from Quepid to external systems, like Jira, Github/GitLab, Discussion Forums

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#410]
**Is your feature request related to a problem? Please describe.**
Quepid is often times used as a query rating / relevancy tuning system.
Once the rating has been done, the following discussion happens in external to Quepid systems, like chat, Jira, a code version issue tracker.

It would be fantastic to have Quepid link to these systems on case level.

**Describe the solution you'd like**
Screenshot will follow shortly based on the recorded design discussion with @epugh 

**Describe alternatives you've considered**
Such alternative could be listing Quepid case links along with Jira links in an excel or some other bookeeping system, which is a very suboptimal solution.
Quepid can and should link deeper into the outside tool set.

**Comment by epugh** [comment]
Here are some tools that *could* be used.  The MVP would be just to add links as HTML links to Quepid...   NO biggie.  But what if we could do a bit of Link Unfurling (like in Slack ;-) ):

* https://github.com/gottfrois/link_thumbnailer
* https://github.com/metainspector/metainspector might be more straightforward...
* https://yuktikhurana.github.io/Slack-Like-Url-Unfurling-In-Rails/
* https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fapp.quepid.com
* https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254
