### ISSUE TITLE
Turn try history into a tree aka git-tree with commit messages

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#411]
**Is your feature request related to a problem? Please describe.**
The try history is currently a flat list of changes applied to the query: 
![Screenshot 2021-09-18 at 12 55 19](https://user-images.githubusercontent.com/123553/133884922-a8322326-f368-4b97-a20f-9afd1233763d.png)

One of the purposes of the try list is to be able to trace back to a particular query formula (stored in a try) and branch off your relevancy tuning / query analysis process from there.

So naturally, the tries are not flat, they are a tree (Screenshot will follow).

**Describe the solution you'd like**
Turn the flat list of tries into a tree.

**Comment by epugh** [comment]
![image](https://user-images.githubusercontent.com/22395/133894314-79cf29db-9d36-4615-aab8-e050acfc253c.png)

**Comment by epugh** [comment]
![image](https://user-images.githubusercontent.com/22395/133894349-c2cbd4cf-3020-4404-96c8-055c1934d9a0.png)

**Comment by epugh** [comment]
![image](https://user-images.githubusercontent.com/22395/133894363-dcf37db3-75fb-4f0f-b222-b9fa44a5efe7.png)

**Comment by epugh** [comment]
![image](https://user-images.githubusercontent.com/22395/133894538-81f0f8e2-0c22-4b26-bd71-d0ec9a96d9a5.png)
