### ISSUE TITLE
Quepid says "Only the top 10 results are used in the scoring calculations" for DCG@30

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#413]
**Describe the bug**
Quepid 6.4.1

![image](https://user-images.githubusercontent.com/123553/133972953-eba0cafc-7e2b-4e9f-b84d-7debb58f1e0a.png)

This label shows that top 10 will be used in scoring, but actually DCG@30 has been configured to include 30 results in calculation.
Is this an issue of the presentation layer?

**To Reproduce**
1. Create a case with a query
2. Configure DCG@30 by copying the code from DCG@10 and modifying the rank to 30.
3. Enable 30 results to display per query
4. Scroll down to the end of the response list and notice the string in the screenshot.

**Expected behavior**
The string should get the number of results included in scoring from the scorer.

**Comment by DmitryKey** [comment]
Confirmed: this issue is still visible on staging

**Comment by epugh** [comment]
Yeah...  so, I think this message is hard coded, and is from the olden days of Quepid when we thought "who would ever want to look more then 10 deep when calculating DCG" <----   As we carried our stacks of punch cards around ;-).

**Comment by epugh** [comment]
Oops, I committed the code to master, https://github.com/o19s/quepid/commit/73a378f9bae777cb504618cdc3361bfec52ff82f

**Comment by epugh** [comment]
@DmitryKey can you give your test another try in staging?  You need a `k` variable in your scorer!!!!!

**Comment by DmitryKey** [comment]
@epugh This will do?
```
var k = 30 // @Rank
var score = 0;

eachDoc(function(doc, i) {
    var d = Math.log2(i+2); // i is the JSindex not the DocRank; 0 vs 1
    var n = Math.pow(2,docRating(i))-1;
    score += d?(n/d):0;
}, k)

setScore(score);

```

**Comment by DmitryKey** [comment]
k=30
<img width="489" alt="Screenshot 2021-09-24 at 10 17 08" src="https://user-images.githubusercontent.com/123553/134634058-382da54f-3c8b-4357-818d-0c1ee680a6ca.png">

k=31
<img width="526" alt="Screenshot 2021-09-24 at 10 17 47" src="https://user-images.githubusercontent.com/123553/134634146-0cba3ac1-c898-4465-bbb1-18c94ac2bfd4.png">

Nice! 

(copying my comment from Slack):
Conceptually, we have 2 things at play here:
* rank k of the scorer as you outlined above
* number of visible results on the screen. If k=31, but number of results is 10, then user might get confused if we say 31 results took part in scoring. 

Perhaps, we need a visual cue saying that you can page forward to see all the results that are participating in the score

**Comment by epugh** [comment]
Thoughts on what the message would be?   We could also have a message like "You are looking at 10 documents, but ratings on 31..   Page to see the rest or change the "Number of Documents to show to 31" to see them all!".   Or maybe, we even have a link "Click here to change the number of documetns to see to match the rating depth" that did it?

**Comment by DmitryKey** [comment]
Can we implement the link? If yes, then, I'd vote for that, because it is fastest for user to adopt.

**Comment by epugh** [comment]
The fix was committed directly to master (oops) so no related PR.  Closing now.
