### ISSUE TITLE
External entity authentication

### ISSUE THREAD

**Issue by danielibars** [o19s/quepid#415]
**Is your feature request related to a problem? Please describe.**
Enable Quepid to allow SSO (Single Sign On) providers like Google with SAML.

**Describe the solution you'd like**
It could be great to have the option to log in to Quepid using External Identity Providers.
as an example:
https://trello.com/login

You can use your Google, Apple, Microsoft, Slack accounts to log in to the tool.

**Additional context**
I'm trying to push in my current job to adopt Quepid, but to make it happens seems like Quepid needs to support Google Authentication for my team to consider it

**Comment by epugh** [comment]
Thanks for this!   So, we did just recently add oAuth to support SSO.   app.quepid.com demonstrates the Google Auth setup, and you can set up your private Quepid to use Google by following the steps in https://github.com/o19s/quepid/blob/master/docs/operating_documentation.md#OAuth, though of course having more instructions would be great.

We can *easily* add other providers beyond the Google and Keycloak that we have done.   

Can you trial the Google Authentication with the hosted version with your team, make sure no hiccups?

**Comment by epugh** [comment]
Chatting with @danielibars and the hosted quepid Google Auth works great.  He is going to look at https://github.com/o19s/quepid/blob/master/docs/operating_documentation.md#OAuth and test it out with their private install.  

Marking as closed, but we can open new issues around the docs or any other things you struggle with!
