### ISSUE TITLE
Viewing tries history jumps to HTTPS

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/quepid#444]
**Describe the bug**
When using Quepid over HTTP and clicking the "Visualize your tries" link under "History", Quepid jumps to HTTPS. Clicking the "Back" link stays on HTTPS and have to switch back to HTTP.

**To Reproduce**
1. When on HTTP, open the search relevance tuning.
2. Click the History tab.
3. Click Visualize your tries. (Note that you are now in HTTPS.)
4. Click back. (You are still in HTTPS and will have to switch back to HTTP.)

**Expected behavior**
Quepid will stay on HTTP if on HTTP.

**Comment by jzonthemtn** [comment]
The change from HTTP to HTTPS happens when clicking "Visualize your tries" (and not when clicking Back).

**Comment by epugh** [comment]
This just blew me up in the demo I just gave....    Argh, we need that same http/https logic to kick in...   want to look?
