### ISSUE TITLE
Allow for importing ratings from a URL

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/quepid#449]
**Is your feature request related to a problem? Please describe.**
No, just a convenience feature.

**Describe the solution you'd like**
It would be nice to be able so share an exported ratings file with others simply by providing them the URL to the file. The users could then import the ratings into Quepid by specifying the URL instead. It would be ideal to have this option for each of the export types (CSV, RRE, LTR) but having it for just CSV to start would be sufficient.

**Describe alternatives you've considered**
None.

**Additional context**
Screenshot of mockup:
![import](https://user-images.githubusercontent.com/13176962/145215657-716364cc-612c-496b-9228-84f7aa91a652.png)
.

**Comment by epugh** [comment]
You could imagine some sort of "Ratings Management Solution" or maybe a "Search Analytics Workshop" tool that is the source of truth for lots of ratings types of files, and we would want to loosely couple that to Quepid...    So this is a great idea!   Then you could imagine maybe in the future we tie a Quepid Case to some third party source of ratings that flow into Quepid as the ratings happen ;-).   The "source of truth" for ratings is elsewhere, and everytime you load Quepid you get the latest ratings!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by epugh** [comment]
;-)

**Comment by epugh** [comment]
Love the tutorial reference...

**Comment by epugh** [comment]
There was another request to import queries with the `options` field populated.   I think we need a complete query importing solution that does queries + ratings in JSON format that covers everything that Quepid can support!
