### ISSUE TITLE
Cases grouping with scoring on group level

### ISSUE THREAD

**Issue by KennyLindahl** [o19s/quepid#462]
The feature that i would like to request is to have groups for cases.
And it would be possible to see the total score summed up by the cases in the group.

Let me give you an example.
Let's say that you have one group per segment of a shopping service, ex Clothes.
Within this segment there is several sub segments (cases), ex jackets, shirts, pants etc.

- **Clothes** (Total score x) <-- This is the group name and the total score is accumulated by the scoring of the children cases
  - **Jackets** (score x)
  - **Shirts** (score x)
  - **Pants** (score x)

To be able to have groups within groups would also be very beneficial, for example:

- **Group name** (Total score of Sub group 1 and 2 accumulated)
  - **Sub group 1** (Total score of the cases)
    - **Sub group case 1.1** (score x)
    - **Sub group case 1.2** (score x)
  - **Sub group 2** (Total score of the cases)
    - **Sub group case 2.1** (score x)
    - **Sub group case 2.2** (score x)

Is this something that you have been thinking about or would be willing to add?

Right now how we solve this is by doing all the ratings in the ex: Jackets, Shirts, Pants and then export in into ex: Clothes.
But that it's not a sustainable solutions when we have many cases.

Thanks for taking your time to read this 😄 
/Kenny

**Comment by epugh** [comment]
I;d love to see more different ways of organizing things...    I've imagined a more proper "dashboard view" over all of your cases, instead of just dropping you into the most recent one...    Where you could link or nest them together, and then see scores that rolled up...    I think there is a LOT we could do in this space.
