### ISSUE TITLE
Query results not rendered on UI for custom API endpoint (Elasticsearch)

### ISSUE THREAD

**Issue by A2Kashyap** [o19s/quepid#465]
**Describe the bug**
Replicating the Elastic-search response structure, from a custom API endpoint, results in empty rows on the UI without data rendered in them. The issue turns out to be empty objects passed in for some fields like "highlight" , "_explanation", and "profile".

**custom API response:**
`{
  "took": 22,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipepd": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 10,
      "relation": "eq"
    },
    "max_score": 200,
    "hits": [
      {
        "_shard": "_shard",
        "_node": "_node",
        "_index": "_index",
        "_type": "_type",
        "_id": 11,
        "_score": 100,
        "_source": {
          "item_type": "DESTINATION",
          "item_id": "uuid",
          "name": "Paris",
          "image": "image url",
          "city": "Paris",
          "country": "France",
          "continent": "Europe"
        },
        "highlight": {},
        "_explanation": {}
      }],
  },
  "profile": {}
}`

**To Reproduce**
1. Goto tune relevance
2. Select "Elasticsearch" engine
3. Provide custom API endpoint that replicates ES response structure
4. Run query
5. Query results are fetched successfully but not rendered correctly

**Expected behavior**
The UI should be able to handle empty/extra objects in the response which are not mandatory for the rendering.

**Screenshots**
![image](https://user-images.githubusercontent.com/43842480/154530201-a8c27e39-b0b5-4e19-b6d7-8d36f1dba9bd.png)

**Workaround**
Ignoring the empty objects, and just sending the "hits" object works. Quick fix suggested by _**Dmitry Kan**_

`{
  "hits": {
    "total": {
      "value": 10,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "indexname",
        "_type": "_doc",
        "_id": "uniqueid",
        "_score": 1,
        "_source": {
          "item_id": "uuid",
          "item_type": "DESTINATION",
          "name": "Paris",
        }
      }]
  }`

**Comment by epugh** [comment]
Thanks for opening this ticket...  I'm going to look at updating `splainer-search` to be more forgiving for the ES JSON.   Hopefully I can grok the unit test structure ;-)

**Comment by epugh** [comment]
Okay, i am using a quick expressjs to serve up the sample json, and I see the same problem!

![image](https://user-images.githubusercontent.com/22395/155003167-94480498-bfe8-4fd0-93e6-4ab16af52a73.png)

I haven't been able to write a unit test yet ;-)
