### ISSUE TITLE
"Missing doc" error when comparing with snapshot in Elastic when using non standard ID

### ISSUE THREAD

**Issue by KennyLindahl** [o19s/quepid#466]
As described, when trying to compare with a snapshot using Elastic when you have a non standard ID set it will result in `Missing doc` error.
The reason is because it does not take into account that you have put in a non standard ID in the settings in `Tune relevancy`.

<img width="1126" alt="Screenshot 2022-02-18 at 16 13 54" src="https://user-images.githubusercontent.com/1323068/154712430-a77fea1f-f75f-4b46-87ea-748b377d2467.png">

The payload looks like this to Elastic (where the ID's are `one`, `two`, `three`, `four` on the `collapseField` field):
```json
{
  "query": {
    "ids": {
      "values": [
        "one",
        "two",
        "three"
      ]
    }
  },
  "size": 3,
  "explain": true,
  "profile": true,
  "_source": [
    "collapseField",
    "collapseField"
  ],
  "highlight": {
    "fields": {
      "collapseField": {}
    }
  },
  "from": 0
}
```
The above doesn't work and i checked it in Kibana as well.

But it should look something more like this:
```json
{
  "query": {
    "terms": {
      "collapseField": [
        "one",
        "two",
        "three"
      ]
    }
  },
  "size": 3,
  "explain": true,
  "profile": true,
  "_source": [
    "collapseField",
    "collapseField"
  ],
  "highlight": {
    "fields": {
      "collapseField": {}
    }
  },
  "from": 0
}
```
The above works, i verified it in Kibana as well. Both if you have an alternative id or if you have the standard `_id` (tested both)

I can also add that it has been reproduced on the latest version of the dev environment of Quepid.
It would be great if you could look into it. I'm completely new to the codebase, but i will see what i can do about it.

Thanks for taking your time to read this,
Kenny

**Comment by KennyLindahl** [comment]
After a bit more digging, i have located the issue to be here in the external Angular module `splainer-search`:
https://github.com/o19s/splainer-search/blob/e572eeb3862948c5b5de7dffce797c548f45f70c/factories/resolverFactory.js#L51-L58

The usage of the function `docResolverSvc.createResolver` in Quepid can be seen here:
https://github.com/o19s/quepid/blob/master/app/assets/javascripts/services/docCacheSvc.js#L56

**Comment by epugh** [comment]
@KennyLindahl this is some GREAT debugging, thank you....    Can you explain a bit about why the two formats that ES expects are so different?   It looks like with a nonstandard ID, you are doing a term seach instead of a lookup.  Is `collapseField` your own name for the field?  It's not a part of the DSL right?   

Do you have an unusual use case?  I'm, surprised that no one has stumbled into this before ;-).    How do you feel about cranking out a unit test in `splainer-search` ?

**Comment by KennyLindahl** [comment]
@epugh Hey, i actually have a fix for it but i seem to have issues running the test.
I tried to make the tests run but i keep getting the following:
```
Disconnected , because no message in 30000 ms.
```
I tried many things, basically all suggestions i could find online but none worked and i feel like i exhausted all options on that for now.

Basically `collapseField` is what i have set as ID field in the "Tune relevance" section.

Please have a look at the PR here:
https://github.com/o19s/splainer-search/pull/101

**Comment by epugh** [comment]
@KennyLindahl did the tests run wihtout your code change?  I'll give it a try as well...    Any chance you are on a new Apple Silicon  mac?

**Comment by KennyLindahl** [comment]
@epugh The tests don't run with or without my changes. And yes i'm on the M1. It's a bit of a hassle with that and Docker, but for Quepid i have resolved all the issues with Docker. It's just running the tests in `splainer-search` that's an issue for now.

**Comment by KennyLindahl** [comment]
@epugh I see that the changes are in Quepid master now, thanks for merging. Any idea when the next release is planned? 😄

**Comment by epugh** [comment]
I'm hoping someone will run through the staging site and make sure a bunch of the various updates I pushed look good, want to give https://quepid-staging.herokuapp.com/sessions/new a quick run through?   Will try to get release out this week.

**Comment by KennyLindahl** [comment]
@epugh Thanks for the update 👍
