### ISSUE TITLE
'ancestry' column in 'tries' table has a length constraint

### ISSUE THREAD

**Issue by korlowski** [o19s/quepid#470]
**Describe the bug**
Column `ancestry` in `tries` table has a length constraint (`varchar(255)`), which limits the maximum number of times that a query can be retried while keeping the ancestry. After several dozen retries, clicking on the `Rerun My Searches!` button in the browser does nothing. The console shows a 500 error and the logs show an exception `ActiveRecord::ValueTooLong (Mysql2::Error: Data too long for column 'ancestry' at row 1):`

**To Reproduce**
1. Go to 'Tune Relevance`
2. Keep clicking on `Rerun My Searches!` until the `ancestry` field reaches the limit of 255 characters.
3. Click on `Rerun My Searches!` again
4. Nothing happens and errors are thrown in the console and logs

**Expected behavior**
Queries should be retryable an unlimited number of times.

**Comment by korlowski** [comment]
The workaround is to backtrack manually to an older try (e.g. by changing the URL from `try/65` to `try/1`), but this drops the `ancestry`. Right now this is good enough for us, but the behaviour doesn't seem intended.

**Comment by epugh** [comment]
Have you tried to change the size of the column?   I hadn't ever thought about what happens when the column gets too long, and it sounds like at a minimum we need a nicer error message!   I wonder if we could just bump the size?  (https://www.tutorialspoint.com/What-is-the-maximum-length-of-MySQL-VARCHAR-column)

**Comment by epugh** [comment]
Okay, looking at the website, it appears that the short column is a known thing, and they recommend just making it bigger.  https://github.com/stefankroes/ancestry#internals

Thoughts on resizing the column to something bigger?    

@korlowski, would you be interested in submitting a patch to properly catch the exception and resize the database column?

**Comment by epugh** [comment]
I did a bit of poking, and I didn't realize that the tree structure hits that 255 limit really quickly. Here is what is stored int he database, and see how long my id's are:

```
Try 0: 1048857773
Try 1: 1048857773/1048857774
Try 2: 1048857773/1048857774/1048857775
```

I can't even run 50 tries sequentially...    Now, if you fork etc, then you can.
