### ISSUE TITLE
Peek at the next page of results only works if you have a full page left

### ISSUE THREAD

**Issue by anegyesi** [o19s/quepid#473]
Peek at the next page of results only works if you have a full page left. So, if you set results visible to 5 and you have 7 results, you can't peek at next page. If you have 10+, you can.

Side note: it would also be useful to be able to close the "peek"s.

**Comment by epugh** [comment]
I was able to peek up to a partial set, but realized that was a large set...

<img width="366" alt="image" src="https://user-images.githubusercontent.com/22395/162427873-41e118f6-59b1-46f3-af7c-ea9f08385017.png">

Going to try on a less then 10!
