### ISSUE TITLE
Deleting all queries

### ISSUE THREAD

**Issue by anegyesi** [o19s/quepid#475]
It would be pretty useful to have an option to delete all queries from a case. My current workaround now is cloning without queries and delete original.

**Comment by epugh** [comment]
Oddly enough the "Delete a Case" button only exists on the Case LIsting page.   I wonder if we had a X or something on the main Case tool bar, maybe next to the Export ubtton and you clicked it and got the "Delete a Case" and "Delete All Queries" options?
