### ISSUE TITLE
Ancestry is limited to 255 chars and can be exceeded

### ISSUE THREAD

**Issue by KennyLindahl** [o19s/quepid#478]
**Describe the bug**
The `ancestry` column in the `tries` table is limited to **255** chars and can be exceeded.
This bug was discovered when many of our cases lost the ability to click "Rerun queries" in the "Tune relevance" panel.
This results in the `/tries` endpoint returning `500 - internal server error`.

**To Reproduce**
If you currently have just under **255** characters in the `ancestry` field in your `try` and you create another try, then it will crash since the ancestry column is limited to **255** characters.

**Expected behavior**
The `ancestry` column in the `tries` table should either have no limit or should be extended when needed.

**Screenshots**
<img width="760" alt="Screenshot 2022-03-16 at 15 38 52" src="https://user-images.githubusercontent.com/1323068/158759711-389bb26a-be60-41de-bed0-2f7b12b6f37b.png">

<img width="1061" alt="Screenshot 2022-03-17 at 08 32 08" src="https://user-images.githubusercontent.com/1323068/158759734-4d0e0e0b-3e45-4b7e-b67a-36358f7324f2.png">

**Comment by KennyLindahl** [comment]
Probably a duplicate of https://github.com/o19s/quepid/issues/470
But isn't it something we could fix from the Quepid side as suggested in my post above?

**Comment by epugh** [comment]
making some progress @KennyLindahl ;-)    Just went into the db and changed the column defintion to "20" to make testing easy!
