### ISSUE TITLE
Queries with , comma aren’t recognised by csv format

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#482]
**Describe the bug**
Queries with , (comma) aren’t recognised by csv format when importing rating into the case

**To Reproduce**
1. Go to specific case
2. Click on 'import into case' and select 'ratings' tab
3. Choose CSV format and click 'browse' , following to select the designated file to import

**Expected behavior**
The Queries + ratings should be imported as correctly

**Screenshots**
<img width="1291" alt="Screenshot 2022-04-05 at 14 21 19" src="https://user-images.githubusercontent.com/5163715/161759120-a91d617d-4bb3-4219-a76c-12dc346d8236.png">

**Additional context**

**Comment by epugh** [comment]
So, this is a "works as designed", however maybe the error message could be better.   Since we column delimit the CSV, if you have a `,` in your query, you need to wrap it it `"` characters.   I'll test that actually works ;-)

**Comment by epugh** [comment]
I dug in, and it turns out we don't handle wrapping with `"` ;-(.
