### ISSUE TITLE
Copy Json data as double quoted keys sorted by key in Explain Query

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#492]
**Is your feature request related to a problem? Please describe.**
using jsoncompare.com to compare too sets of queries, and we need keys to be `"` and the keys in order.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by risdenk** [comment]
There are a bunch of references to either property names or json key names MUST be double quotes. Here is one such example: https://www.w3schools.com/js/js_json_syntax.asp

> A name/value pair consists of a field name (in double quotes), followed by a colon, followed by a value:

and

> JSON names require double quotes.
