### ISSUE TITLE
Limited encoding renders snapshots unusable

### ISSUE THREAD

**Issue by KennyLindahl** [o19s/quepid#499]
**Describe the bug**

If you have a search result that contains special characters (ex "fēnix") it will render the snapshots unusable.
It will not be possible to compare with snapshot or export it.

It will produce the following error:
```command
'\xC4\x93nix ...' for column quepid.snapshot_docs.explain at row 1
```

**Issue & solution**

On the `explain` column in the `snapshot_docs` table, it has the wrong encoding and it needs to be changed to handle special characters.

Issue:
- `Encoding:` cp1252 West European (latin1)
- `Collation:` latin_swedish_ci

Fix:
- `Encoding:` UTF-8 Unicode (utf8mb4)
- `Collation:` utf8mb4_general_ci

<hr/>

**To Reproduce**
1. Have a text with special characters in any of the search results
2. Create snapshot

**Expected behavior**
Should create snapshot without error.

<hr/>

**Final thoughts**
I suggest that the encoding utf8mb4 should be used everywhere possible to avoid future problems.

**Comment by epugh** [comment]
Any thoughts on how to make this change?   Is this something that can be done "in place" with a SQL update or do I need to create a new field with the right encoding, copy all the data, and then rename it maybe???

**Comment by epugh** [comment]
I reached out to the provider of our production db, JawsDB for some support on how to actually make this happen.

**Comment by epugh** [comment]
Looks like this is what gets run:

```
/* 11:32:49 AM Docker Quepid Dev quepid_development */ ALTER TABLE `snapshot_docs` CHANGE `explain` `explain` MEDIUMTEXT  CHARACTER SET utf8mb4  COLLATE utf8mb4_general_ci  NULL;
```

I need to do some testing, and ensure backups are fully baked before running this on app.quepid.com.

**Comment by epugh** [comment]
Okay, I worked with our database provider and they did some magic, so now the migration worked!
```
Running bin/rake db:migrate on ⬢ quepid-staging... up, run.3078 (Hobby)
I, [2022-05-18T22:32:54.850138 #4]  INFO -- : Migrating to BetterTextEncodingInDatabase (20220513180755)
== 20220513180755 BetterTextEncodingInDatabase: migrating =====================
== 20220513180755 BetterTextEncodingInDatabase: migrated (171.9097s) ==========
```


@KennyLindahl any chance you could test out using the http://quepid-staging.herokuapp.com staging version of Heroku the change to the database with your query?   Would love proof positive it's all working before I ship these changes to production!

**Comment by KennyLindahl** [comment]
@epugh Great, thanks for fixing it! I don't have time to test it but i'm pretty sure it has resolved the issue after looking at the MR 😄
