### ISSUE TITLE
Export functionality should export the data from the Case and all of it's queries, not just the rated queries...

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#501]
**Describe the bug**
When using case export fucntionality it was noticed that the exported data is as same as the data of the case it was originally cloned from , which means if the query gave 2 results in the original case and was cloned to a new case , changes made to the relevance algo which affected the search results to reflect 10 results but when it was exported the csv still showed 2 results , which is incorrect.

**To Reproduce**
1. Go to 'Case'
2. Click on 'export'
3. Scroll down to 'basic' (or detailed)
4. Observe the corresponding search results for given queries , if different from the case it was cloned will not be reflected. Also the query is not exported if it has no results.
Ref : https://github.com/o19s/quepid/blob/0fb2fe2d498ea508be78e2117dd32d0afbdfd73b/app/assets/javascripts/services/caseCSVSvc.js#L265

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by epugh** [comment]
This is fixed!
