### ISSUE TITLE
Not able to delete the unwanted query from the case

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#502]
**Describe the bug**
I am unable to delete query from the case AFTER i ageeed to a prompt saying 'do not prompt...' from Quepid

**To Reproduce**
1. Go to 'case'
2. Click on 'expand query'
3. Click on 'Delete Query'
4. After repeated delete query actions , you will be prompted with a dialog for confirmation to not prompt for delete
5. The time you hit 'Delete Query' no change will be observed , no delete action is performed.

**Expected behavior**
The requested query should be deleted.

**Screenshots**

![Screenshot 2022-04-29 at 11 47 58](https://user-images.githubusercontent.com/5163715/165924480-58a0e735-bbc2-4f77-b49c-37fadf073b81.png)

**Additional context**

**Comment by epugh** [comment]
can you retest this one?   I tested locally and it all worked....  I'm wondering if the app was in a werid state????

**Comment by atarora** [comment]
Yes , I am still able to reproduce this on Firefox , this is the dialog , I was referring to , after this , we cannot delete anymore.

![Screenshot 2022-05-10 at 11 00 28](https://user-images.githubusercontent.com/5163715/167615285-6c3be5a4-fa02-48db-a5fa-dcd090b440fa.png)

**Comment by epugh** [comment]
Still can't duplicate this one...

**Comment by atarora** [comment]
Closing as Fixed / not reproducible on Chrome , Safari and Firefox on my side either.
