### ISSUE TITLE
'Information need' import doesn't works for an empty case

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#507]
**Describe the bug**
When I try to import information need csv into a case after deleting all the queries in the case , it is not imported (no errors were seen on console)

**To Reproduce**
1. Go to 'case' (preferabbly the case with some queries)
2. Click on 'delete all queries'
3. Click to 'Import'
4. Select the 2nd tab saying 'Information needs''
5. Choose the csv with designated format and click 'import''

**Expected behavior**
The listed queries + information needs should have exported but instead a blank case is returned with success.

**Screenshots**

**Additional context**

**Comment by epugh** [comment]
Thanks for opening this...  So I think I know the key issue, which is that I assumed that when you imported info needs, you would be doing it for ALREADY EXISTING queries in Quepid.   It all keys off the `query_id`, so you would export your queries, then add your info needs to the csv, and then import it back in.  

Indeed, I added this PR that valides every `query_id` exists: https://github.com/o19s/quepid/pull/508

However, I think maybe I've gone in the wrong direction, and that we should just export the `query,information_need` and import it...  so we just use the query to match on, not the query_id....?    THoughts??

**Comment by atarora** [comment]
Keeping query ids makes sense ! 
My problem is if I removed all the queries from the case and ensure that it is empty , how m I still retaining the reference of query ids ?
https://app.quepid.com/case/5686/try/0?sort=query&reverse=false
[Zero_hits_ee_wholesale_query_sets - ee_wholesale_query_sets.csv](https://github.com/o19s/quepid/files/8665549/Zero_hits_ee_wholesale_query_sets.-.ee_wholesale_query_sets.csv)
is what I am trying to add into the case.

But after multiple tries , I still get empty case.

**Comment by epugh** [comment]
yeah, so, since you remove the queries from teh case, those queries with those id's are all gone...  i actually thing I *shoudn't* use the query id, and just use the query text....
