### ISSUE TITLE
Showing multiple query scores

### ISSUE THREAD

**Issue by moshebla** [o19s/quepid#51]
**Is your feature request related to a problem? Please describe.**
This is an improvement which will help measuring query scores from different angles.

For all intents and purposes, https://github.com/o19s/quepid/issues/50 is in fact a private case of the approach suggested here.

**Describe the solution you'd like**
Right now a single query score is computed and displayed. A single scorer is selected and used to compute those scores, which is then aggregated to become the Case Score.

**Describe alternatives you've considered**
We would like to be able to optionally show multiple scores - e.g. CG, NDCG@10, ERR, P@1, P@10 etc. Visually it's definitely possible to show at least 3 scores per query, and this can provide great benefit while tuning relevance - during the initial discovery and research phases, but also for on-going efforts and regression testing.

All the infrastructure for this is already built-in into quepid. Our suggestion is to allow picking more than one scorer to be used for a case. Each scorer will compute it's own score per query, and all computed scorers will be displayed with a clear indication of the scorer name used to produced that score.

A case score can then be decided to be the mean of all query-scores for selected scorers (one or more).

Comparing snapshots should also take all scorers into account (which is in-fact the goal of this change)

Please let me know your thoughts and if all the above makes sense I can go ahead and implement this change.

**Comment by epugh** [comment]
I've talked to a number of stakeholders of Quepid about this, and the consensus has been a big +1 on this effort.   

In a related effort @binarymax has written a number of scorers already in JavaScript for Quepid, however they aren't shipped with Quepid.  @nathancday has been looking at getting them loaded into the `default_scorers` table on startup   That effort should line up nicely with this one.

**Comment by epugh** [comment]
I'm going to reopen this, though it may be a bit before we get to this!
