### ISSUE TITLE
AP@10 computation is incorrect

### ISSUE THREAD

**Issue by david-fisher** [o19s/quepid#518]
**Describe the bug**
AP@10 is not computed according to the formulation of one precision point for each relevant document.

**To Reproduce**
In Quepid, using AP@10 as the metric, search for Princess Bride in tmdb
The top ranked document is Princess Bride. Rate it 1 (relevant)
rate the remaining nine documents 0 (irrelevant)
AP@10 is shown as 0.29

**Expected behavior**
AP@10 should be 1.0

**Screenshots**
![Screen Shot 2022-05-24 at 3 01 43 PM](https://user-images.githubusercontent.com/1194968/170112585-553378fd-6423-4f11-98d0-cac81c3da33f.png)

**Additional context**

When computing average precision, we compute a precision value each time we encounter a relevant document in the ranked list. We then divide the sum of those precision points by the total number of relevant documents. Doing so allows us to treat all missing relevant documents as occurring at rank infinity, effective precision 0. This is discussed in [https://stackoverflow.com/questions/49275764/ir-calculate-average-precision-from-varying-relevant-documents-to-rank-k](url)

trec_eval [https://github.com/usnistgov/trec_eval](url) produces the expected behavior:

dfisher@earthsea test % cat res.ten
301	Q0	FR940202-2-00150	1	  2.129133		STANDARD
301	Q0	FR940202-2-00151	2	  1.724760		STANDARD
301	Q0	FR940202-2-00154	3	   2.104024	        STANDARD
301	Q0	FR940203-1-00036	4	  1.912871		STANDARD
301	Q0	FR940203-1-00038	5	  1.800881		STANDARD
301	Q0	FR940203-1-00039	6	  1.870957		STANDARD
301	Q0	FR940216-1-00014	7	  1.677013		STANDARD
301	Q0	FR940303-1-00006	8	  1.999081		STANDARD
301	Q0	FR940303-1-00012	9	  1.841413		STANDARD
301	Q0	FR940303-1-00014	10	  1.732111		        STANDARD
dfisher@earthsea test % cat qrel.ten
301	Q0	FR940202-2-00150	1
301	Q0	FR940202-2-00151	0
301	Q0	FR940202-2-00154	0
301	Q0	FR940203-1-00036	0
301	Q0	FR940203-1-00038	0
301	Q0	FR940203-1-00039	0
301	Q0	FR940216-1-00014	0
301	Q0	FR940303-1-00006	0
301	Q0	FR940303-1-00012	0
301	Q0	FR940303-1-00014	0
dfisher@earthsea test % ../trec_eval qrel.ten res.ten
runid                 	all	STANDARD
num_q                 	all	1
num_ret               	all	10
num_rel               	all	1
num_rel_ret           	all	1
map                   	all	1.0000
gm_map                	all	1.0000
…
P_5                   	all	0.2000
P_10                  	all	0.1000
P_15                  	all	0.0667
P_20                  	all	0.0500
P_30                  	all	0.0333
P_100                 	all	0.0100
P_200                 	all	0.0050
P_500                 	all	0.0020
P_1000                	all	0.0010

**Comment by epugh** [comment]
I'd love an updated version of our scorer ;-)

**Comment by epugh** [comment]
You can edit it via the custom scorer stuff, and if you have a candidate, then we can update https://github.com/o19s/quepid/blob/master/db/scorers/ap%4010.js

**Comment by david-fisher** [comment]
AP @ k does not make any sense, AP is the average precision at 100% recall. While you could compute it by setting the size of the set of relevant documents to k, that isn't really AP. P@k is a more appropriate metric.

To implement a custom scorer to compute AP, I need access to the ranked list, and the full set of the non-zero relevance judgments. Cursory inspection of the scorers source bits (primarily the ScorerFactory) did not identify where in code those items might be. It would be helpful to have someone point me to relevant portions of the source.
