### ISSUE TITLE
Use fields in Elasticsearch query template search responses

### ISSUE THREAD

**Issue by gossu** [o19s/quepid#538]
Right now, when working with query templates, quepid only looks at `_source` of result documents when building query results view.

I would like quepid to also look at the `fields` section of result documents. 

The `fields` section contains fields that are generated with "runtime fields" and "scripted fields" features in Elasticsearch. It is therefore data that does not belong to original documents sent to Elasticsearch, but is generated on the search time instead.

**Describe alternatives you've considered**
Currently seems like the only option to use `fields` in quepid is by running regular search queries against Elasticsearch (without query templates). Being able to use query templates is very convenient though so it is a pity that `fields` is not supported there.

**Comment by epugh** [comment]
I'd love to see this added...  Would you be interested in tackling this?

**Comment by epugh** [comment]
I think this is closed by #706 !!   THank you for reporting it.
