### ISSUE TITLE
Snapshot export should contain total number of search results

### ISSUE THREAD

**Issue by renekrie** [o19s/quepid#539]
**Is your feature request related to a problem? Please describe.**
I'm trying to derive from a snapshot export file some information on how much search results vary between queries. It would be useful to know the total number of search results - at the moment the snapshot just contains the k top doc ids per query. 

**Describe the solution you'd like**
I'm not sure where in the export this information should end up. I guess it would make sense to add a column to the existing snapshot export. The `count` value would then be repeated for all docids of a query but I think that's okay and be better than creating yet another export file.

**Comment by epugh** [comment]
Combination of #550 and #544 added storing in a snapshot the score and if it was all rated...    We don't have the total number yet.

**Comment by epugh** [comment]
We need a much more robust solution for exporting data....   Almost like a graph query language based approach for selecting what you want to export.   Or, a much richer GUI with checkboxes etc....   

For now, and I am a bit embarrased by it...  I'm going to just expose in the export UI the links to run the .json end points!

**Comment by epugh** [comment]
Okay, here is what I have:
![image](https://user-images.githubusercontent.com/22395/186451606-198ed2ec-b22a-4c60-a1ea-052981ed9a72.png)

**Comment by epugh** [comment]
Since I was there, why not expose more of the API's?  
![image](https://user-images.githubusercontent.com/22395/186454481-99017b19-bf86-4a15-80e2-a50a5794e5f9.png)
