### ISSUE TITLE
Scorer v1-527 is redundant with scorer v1-520

### ISSUE THREAD

**Issue by david-fisher** [o19s/quepid#541]
**Describe the bug**
There are two differently named copies of the same scorer function

**To Reproduce**
Load Quepid
View Scorers
Add a scorer to see the sources.

**Expected behavior**
There should only be one name for any given scoring function.

**Comment by epugh** [comment]
i've been avoiding this one for a few years...   because I am nervous about running the SQL migrations ;-).   

However, yeah, it's annonying, and i guess it's time!

**Comment by epugh** [comment]
See #542  for some code we need

**Comment by epugh** [comment]
Okay, we're done.  I also marked it in the code and the name to be less attractive to people!

![image](https://user-images.githubusercontent.com/22395/182627374-2c58fb9d-f660-41b6-aab6-784a7fc6f3b3.png)

**Comment by epugh** [comment]
Thansk for this @david-fisher
