### ISSUE TITLE
Updated production docker-compose.yml

### ISSUE THREAD

**Issue by OkkeKlein** [o19s/quepid#554]
[docker-compose.yml.txt](https://github.com/o19s/quepid/files/9423530/docker-compose.yml.txt)

Current installation guide didn't work for me. Above is the docker-compose.yml that worked for me with some remarks:

1. Redis needs to be installed. Not only to get current version running (dependency of sidekiq), but also to make it future proof.
2. Unless you are only using search engine endpoints without TLS/SSL(HTTPS) you need to also install Nginx with some certificates. The readme.md contains the follwing text that may need to be included in installation quide:

> There's a directory .ssl that contains they key and cert files used for SSL. This is a self signed generated certificate for use in development ONLY!
> 
> The key/cert were generated using the following command:
> 
> openssl req -new -newkey rsa:2048 -sha1 -days 365 -nodes -x509 -keyout .ssl/localhost.key -out .ssl/localhost.crt
> PS: It is not necessary to do that again.
> 
> The docker-compose.yml file contains an nginx reverse proxy that uses these certificates. You can access Quepid at https://localhost/ or http://localhost/. (Quepid will still be available over http on port 80.)

So to get this working with the attached docker-compose file you also need to copy the directory `.ssl` from https://github.com/o19s/quepid to your installation directory or create a '.ssl' directory with your own certificates. Name them certificate.key and certificate.crt and it will work with [nginx.conf.txt](https://github.com/o19s/quepid/files/9423672/nginx.conf.txt) (copy this file to installation directory)

**Comment by epugh** [comment]
Thanks for submitting this, so great stuff....

**Comment by epugh** [comment]
would you like to take a stab at editing https://github.com/o19s/quepid/wiki/Installation-Guide ????

**Comment by epugh** [comment]
Fixed in #557
