### ISSUE TITLE
Add a media: option to allow media files to be played on mouseover

### ISSUE THREAD

**Issue by flaxsearch** [o19s/quepid#56]
It would be great to be able to play media files from any links returned in the result list, perhaps using a 'media:' option like the 'thumb:' option. This would be useful for those reviewing indexed media files and help them to easily rate them.

**Comment by peterdm** [comment]
Not to be "that abstraction guy", but why not instead (or in addition) add a tab with two boxes inside "Tune Relevance"

Box 1.  Add custom Script-tags & CSS to <head> (append)
Box 2.  Customize result summary (show angular) . ... provide variable format for accessing record.
```
<div class="col-summary" ng-class="{true: 'col-summary-img', false: ''}[doc.hasThumb()]">...
```
(with a "Reset" button of course)

Then, not only could clients override styles and change colors, etc... but they also could help narrow the perceived relevance gap between the Quepid SERP and their production SERP.

**Comment by worleydl** [comment]
@peterdm I will add your idea as a separate issue.  It will involve some cleanup of the default template but should be workable.  I also need to read up on best practices of allowing something like that to keep it sandboxed so custom styles/other things don't escape and break the main site.
