### ISSUE TITLE
Add "Unshare case" feature

### ISSUE THREAD

**Issue by DmitryKey** [o19s/quepid#564]
**Is your feature request related to a problem? Please describe.**
When drafting query cases, I can start sharing them with a team, but later change my mind.
Currently Quepid only allows one-way sharing, but no unsharing functionality is available.

**Describe the solution you'd like**
Flip "Share case" to "Unsare case" if it is shared.

**Describe alternatives you've considered**
First cloning, then deleting the shared case could be one workaround.

**Comment by epugh** [comment]
will push this live in a few...

**Comment by epugh** [comment]
Just fixed darn jupyterlite notebooks, so shipping this too to prod

**Comment by epugh** [comment]
Yep....
