### ISSUE TITLE
Number of results to show is not preserved when cloning a case

### ISSUE THREAD

**Issue by MassimilianoUngheretti-TomTom** [o19s/quepid#565]
**Describe the bug**

**To Reproduce**
1. Create a case
2. Edit the "Number of Results to Show" property under "Tune Relevance" to e.g. 42 (default = 10).
3. Clone the case

**Observed behavior**
The new case has Number of Results to Show"=10 (default)

**Expected behavior**
The new case has the same "Number of Results to Show" as the cloned case.

**Comment by MassimilianoUngheretti-TomTom** [comment]
I see that in the [cloning function](https://github.com/o19s/quepid/blob/12a9a0bf7e462e9d2e5ebd51b84abb955b8c40f4/app/models/case.rb#L181) there's a missing statement for the `number_of_rows` property.

**Comment by epugh** [comment]
We probably should be using some sort of `.clone` function that ActiveRecord supplies, this has bit us before....    WOuld you be interested in submitting a patch?  Either a `.clone` or just explicitly copying that line!
