### ISSUE TITLE
Consolidate scorers in schema

### ISSUE THREAD

**Issue by worleydl** [o19s/quepid#58]
**Describe the bug**
Less of a bug and just cleanup to the schema.  Scorers and DefaultScorers overlap each other enough that they can be merged to cleanup some code.  Consolidate the scorers into one `scorers` table with a `default` flag and any other fields that may need be necessary and remove the `default_scorers` table.

**Additional context**
This will require changing the schema then updating the rails and angular bit to make use of one table versus two different ones.

**Comment by epugh** [comment]
Any progress on this ticket?   I agree that it's a good idea, however I'm nervous about stacking up lots of "tech debt" refactoring ideas without having some movement ;-)  I don't think we as a community are mature enough to manage a deep backlog of ideas effectively.
