### ISSUE TITLE
Add RR@10 to https://quepid.com/docs/#scorers

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#611]
Can we get this table updated with the new RR@10?

**Comment by epugh** [comment]
Docs go into https://github.com/o19s/quepid-web

**Comment by david-fisher** [comment]
All of the other entries use @5, RR@10 may look funny.

**Comment by david-fisher** [comment]
update in PR: add RR@10 to the scores table #39 in  https://github.com/o19s/quepid-web

**Comment by epugh** [comment]
Thank @david-fisher !
