### ISSUE TITLE
Changing the scorer , doesn't refresh

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#613]
**Describe the bug**
If I happen to changes the existing scorer on the case , I expect the page to refresh and apply the scores per the new scorer , but in reality , that doesn't happens

**To Reproduce**
1. Go to 'case'
2. Click on 'select scorer'
3. Select the new scorer from the list
4. Notice the page doesn't refreshes and the scores per the new scorer isnot applied.

**Expected behavior**
The case should refresh applying the scores per the new scoring algo.

**Screenshots**

**Additional context**

**Comment by david-fisher** [comment]
I am unable to reproduce the issue on app.quepid.com when logged in as myself.  It does take a few moments to update the scores, but they do. The javascript console shows the expected log messages when setScorerForCase is called on update.

This is puzzling, as I did see the misbehavior on the shared screen Atita showed.

**Comment by epugh** [comment]
I did a pretty deep dive and found that swapping scorers would lose their labels.   I fixed it in #717  and I am *hoping* it fixed this problem as well...
