### ISSUE TITLE
Should we track "Not Rateable" query/doc pairs in the Rating interface?

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#626]
**Is your feature request related to a problem? Please describe.**
If you have a query/doc pair that you feel isn't rateable, should we capture that?  We offer a skip option, but what aobut if you can't rate it?

**Describe the solution you'd like**
A "Can't Evaluate this one" button1

**Comment by david-fisher** [comment]
I don't understand what that would mean. For every query/document pair, it is always possible to say, nope! or Yes!

Or are you trying to suggest that there is a query whose intent is so opaque it can't be judged?

**Comment by epugh** [comment]
Exactly!   Often we see raters faced with "I don't get what this query is about, or what this doc is about".....   in the current workflow you can "Skip" the query/doc pair, but then it will have a equal chance of coming back....    And we don't ahve any way of capturing that feedback...

**Comment by david-fisher** [comment]
Then perhaps we actually need one for confusing queries and one for confusing documents. Although, if you can't figure out what a document is about, it is irrelevant, it would seem... For that matter, if you can't figure out what a query is about, all documents are irrelevant to it...

**Comment by epugh** [comment]
Yep...   practically, folks won't probably tell you which they can't figure out...    So at least knowing "this one is confusing" would give you some datum to look at...
especially once we support multiple raters per query/doc pair.

**Comment by epugh** [comment]
i also thinking makign the "opt out" easy ensures that folks won't be overly optimistic and just do a rating in order to do a rating...   People are hard!

**Comment by david-fisher** [comment]
In the context of multiple raters, do we really want to exclude a query/doc pair from consideration by the other raters because one rater didn't get it?

**Comment by epugh** [comment]
good question..  I think not...  so in that case, one rater might say"I don't get it", and the other two might rate it...
the "skip" would be it's own thing...   or we use a magic number like -999 to mean I don't get it....

**Comment by david-fisher** [comment]
If we want to let them skip and not see it again, but others can see it, we probably need a separate table to keep track of user Fred can't figure out query 13789, stop showing it to them... Putting magic numbers in the actual ratings will require post-processing to groom them out. My nDCG will be hideous if there is a -999 rating available to someone...

Can we try telling the story in a more goal-based fashion?

Fred wants to rate documents. Fred discovers that he doesn't understand the query intent for one of the queries. Fred doesn't want to rate any more documents for that query. Fred selects the rating, "I don't get this query", and the query is removed from further rating consideration by Fred. Barney, Wilma, and all other users can still rate that query.

And the corollary:
Fred wants to rate documents. Fred discovers that he doesn't understand the content of one of the documents. Fred doesn't want to rate any more queries for that document. Fred selects the rating, "I don't get this document", and the document is removed from further rating consideration by Fred. Barney, Wilma, and all other users can still rate that document for any query that retrieves it.

So, we have a filter on the list of items to consider keyed on query, and one keyed on document id. When Fred judges, the candidates to judge are filtered prior to presentation. If Fred updates his filters, the candidates to judge are refiltered.
