### ISSUE TITLE
Node Install Failing in Docker? ('Your distribution, identified as "buster", is not currently supported")

### ISSUE THREAD

**Issue by h1d3m3** [o19s/quepid#7]
Not sure if this has something to do with my environment or somehow the build is not working correctly.

**Describe the bug**
Looks like the install/build of Node fails when running ./bin/setup_docker

**Desktop (please complete the following information):**
 - CentOS Linux release 7.6.1810 (Core)
- Docker version 1.13.1, build b2f74b2/1.13.1

**Expected behavior**
Should just complete the docker setup.

**To Reproduce**
- ./bin/setup_docker
- Gets to this point and exits setup without completing.

> + apt-get install -y lsb-release > /dev/null 2>&1
> + '[' 'X lsb-release' '!=' X ']'
> + print_status 'Installing packages required for setup: lsb-release...'
> + echo
> + echo '## Installing packages required for setup: lsb-release...'
> + echo
> + exec_cmd 'apt-get install -y lsb-release > /dev/null 2>&1'
> + exec_cmd_nobail 'apt-get install -y lsb-release > /dev/null 2>&1'
> + echo '+ apt-get install -y lsb-release > /dev/null 2>&1'
> + bash -c 'apt-get install -y lsb-release > /dev/null 2>&1'
> ++ lsb_release -d
> ++ grep 'Ubuntu .*development'
> ++ echo 1
> + IS_PRERELEASE=1
> + [[ 1 -eq 0 ]]
> ++ lsb_release -c -s
> + DISTRO=buster
> + check_alt SolydXK solydxk-9 Debian stretch
> + '[' Xbuster == Xsolydxk-9 ']'
> 
> [... snip ...]
> 
> + print_status 'Confirming "buster" is supported...'
> + echo
> + echo '## Confirming "buster" is supported...'
> + echo
> + '[' -x /usr/bin/curl ']'
> + exec_cmd_nobail 'curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_8.x/dists/buster/Release'\'''
> + echo '+ curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_8.x/dists/buster/Release'\'''
> + bash -c 'curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_8.x/dists/buster/Release'\'''
> 
> ## Confirming "buster" is supported...
> 
> + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/buster/Release'
> 
> ## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
> 
> + RC=60
> + [[ 60 != 0 ]]
> + print_status 'Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
> + echo
> + echo '## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
> + echo
> + exit 1
> ERROR: Service 'app' failed to build: The command '/bin/sh -c curl -skL https://deb.nodesource.com/setup_8.x  | bash -x -' returned a non-zero code: 1

**Comment by epugh** [comment]
Humm..  The magic of Docker is supposed to prevent this!   I notice your docker is 1.13, and at least locally I am on 19.03.1...   Could there be a version of Docker issue?

**Comment by h1d3m3** [comment]
Thanks for the response.

Yeah, that version was pretty old :-) Tried updating docker (now Docker version 19.03.2, build 6a30dfc) and it still fails at the same point.

```
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/buster/Release'
## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```
Not that familiar with node, but somehow the "buster" distro seems to be not supported? Its also possible I'm not finding the actual problem.

**Comment by epugh** [comment]
Hi @h1d3m3 Today @worleydl and I were trying to runt he build and getting SSL related issues.  We modified the Dockerfile to be the `-stretch` version, and now everything runs.   Would you mind taking another spin?   Our theory is that Buster is new, and things aren't working fully, and that Stretch will work.

**Comment by epugh** [comment]
@h1d3m3 if you are still having the issue, please let me know, i'd love to debug it with you.  I'm going to close the issue for now, and please reopen it!
