### ISSUE TITLE
Looking for Missing Docs Doesn't Render UI for OS

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#700]
**Describe the bug**
I thought I could do `overview:trek`, but that didn't work.  Then I tried just `trek` and I got matches, but they don't render in the UI...

**To Reproduce**

**Expected behavior**
Just like in Solr, I should see the docs that my query matched...

**Screenshots**
<img width="574" alt="image" src="https://user-images.githubusercontent.com/22395/233797170-f6ba7290-fd84-4b33-bf7c-5a455869738a.png">

**Additional context**

**Comment by epugh** [comment]
We should either figure out how to make a Lucene query work in OS, or we should rework the docs to say you can't do a LUcene query for OS/ES...

**Comment by epugh** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/22395/233797310-691847a8-f5e4-4279-a993-e9f1c91d22e2.png">

**Comment by mkr** [comment]
For Solr we send the query as the `q` parameter which gives a lot of flexibility. For ES/OS we just replace the `#$query#` placeholder in your configured query with the entered keywords. This supports Lucene syntax only if your query uses a query type that does so, e.g. the [query_string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html).
