### ISSUE TITLE
Sortable columns on the http://app.quepid.com/cases

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#708]
**Is your feature request related to a problem? Please describe.**
I'm always bugged when I have to dig in to find which was the last case i worked on , some may have almost similar names and hence I may like to get to the case that i 'ran last' or the one that had highest 'score' , currently i guess 'id' field is used to sort view of all cases.

**Describe the solution you'd like**
It would be nice to have some sortable columns like 'Last Run on' or 'Last Score' (possibly # of queries?) on the http://app.quepid.com/cases

**Describe alternatives you've considered**
When such is needed , I go back and scroll through the list (in my case is 8 pages = 80 cases) and go to the one , that had the most recent 'Last Run on' value

**Additional context**

**Comment by epugh** [comment]
@david-fisher mentioned he wished for this too....
