### ISSUE TITLE
Cloning a Case Loses Advanced Settings

### ISSUE THREAD

**Issue by jvia** [o19s/quepid#725]
**Describe the bug**
When cloning a case the headers stored under advanced settings are lost. 

**To Reproduce**
1. Create a case with custom headers.
2. Clone the case.
3. Notice that the headers under the advanced settings are lost. This is more noticeable when using a search engine that requires authentication.

**Expected behavior**
When cloning a case, I would expect all settings to be cloned.

**Screenshots**

**Additional context**
Tested on Quepid 6.13.0.

**Comment by epugh** [comment]
Fixing this issue once and for all..   everytime we add an attribute to `Try` we forget to add it to the clone!

**Comment by jvia** [comment]
Nice! I’ve also notice this issue showing up with permissions—when cloning a case with specific team permissions those are lost. But that’s also a product question since both ways seem valid to me.

**Comment by epugh** [comment]
@jvia would you be interested in taking a crack at adding an option on the "clone" UI?   We ask if you want to preserve try etc, maybe we should be explicit and ask about preserving team perms?   Sometimes I clone just for myself, but other times I clone and want to share iwth team...    (Maybe a new issue as well?)

**Comment by epugh** [comment]
Also, @jvia you might be interested in #703 ...    I tried to validate the problem and didn't quite see it...   would love independent confirmation.

**Comment by jvia** [comment]
@epugh Sure! Would you mind giving me a brief listing of roughly which files I would need to update? I am not _super_ familiar with Rails or Angular, but I think I could manage once I know what to change.

**Comment by epugh** [comment]
So, the debugger in your browser isy your friend!   You can edit the JS files and just reload in the browser to see things happen.   https://github.com/o19s/quepid/tree/main/app/assets/javascripts/components/clone_case has the component for the UI.   https://github.com/o19s/quepid/blob/main/app/controllers/api/v1/clone/cases_controller.rb is the server side.   Please ping me with any questyions as you learn!   Read the README ;-). And let me know where it isn't clear.
