### ISSUE TITLE
A three point custom scorer shoudl support keyboard shortcuts

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#738]
**Describe the bug**
a custom scorer with 0,1,2 doesn't show the `a`,`s`,`d` keyboard bindings.

**To Reproduce**
Make a three point scorer, not a two point, and not a four point..  A two poin.

**Expected behavior**
keyboard bindings!

**Screenshots**

**Additional context**

**Comment by depahelix2021** [comment]
I think it should be `s` `d` `f` instead of `a` `s` `d` so that's what I did but we can do a,s,d if you really prefer.
