### ISSUE TITLE
Enable "thumb" as type in json to include image files in results

### ISSUE THREAD

**Issue by OkkeKlein** [o19s/quepid#790]
{"name": "poster_path", "type":"thumb", "prefix": "https://www.example.org/images"}  should work same as 
{"name": "poster_path", "type":"image", "prefix": "https://www.example.org/images"}

**Comment by epugh** [comment]
Can you give me a bit more context?   The other week when this first came up, I totally thought I knew exactly what to change, but now when I sat down to put this in, I can't quite remember...    

I did a case with TMDB, and with the field settings: `id:_id, title:title, overview, cast, image:poster_path` and it worked just fien.  I think maybe you are meaning somewhere else??   

<img width="697" alt="image" src="https://github.com/o19s/quepid/assets/22395/36bc9e2e-a2e7-477e-b054-214bf3e20db6">

**Comment by epugh** [comment]
Oh wait, I found the Slack convo...  "formatImageUrl"

**Comment by epugh** [comment]
This is now on app.quepid.com

**Comment by OkkeKlein** [comment]
Confirm it works.

**Comment by epugh** [comment]
thanks @OkkeKlein
