### ISSUE TITLE
Link "return to case" to the actual case

### ISSUE THREAD

**Issue by OkkeKlein** [o19s/quepid#796]
![image](https://github.com/o19s/quepid/assets/4016244/793ca75e-adf1-4c7b-bdb8-6007d4c23d48)

**Comment by OkkeKlein** [comment]
Are you sure that it would go the the last case you looked at? Because it always goes to wrong one for me.

**Comment by epugh** [comment]
Actually not positive on the "last case", I need to dig a bit more into the tracking code to make sure it works.

**Comment by epugh** [comment]
also, just pushed out the fix to app.quepid.com
