### ISSUE TITLE
When using basic auth credentials in URL the query gets cut short

### ISSUE THREAD

**Issue by OkkeKlein** [o19s/quepid#798]
**Describe the bug**
After adding credentials to the Search Engine Request Handler input, the direct Solr query returns a 404 as the URL is cut short. `/serp1?q=term&fq=bs_status:` does not contain the value to filter on. Nor do any of the other filters show in the request..

The request works fine without credentials.

**To Reproduce**
1. Go to tune relevance
2. Add credentials
3. Click "Rerun my searches"

**Comment by epugh** [comment]
Once #788 is done, this will be an easy fix....

**Comment by epugh** [comment]
Need to push these changes live ;-).  version 7.10

**Comment by epugh** [comment]
doing some testing...  and so interestingly the `http://reader:reader@mysolr.com` approach does NOT work with the proxy...   I think becuase that url pattern gets cut out..    Moving to using the explicit basic auth field is goign to fix a couple of issues I suspect ;-)

**Comment by epugh** [comment]
okay, so, I fixed this proxy thing in #1015 by actually digging it out of the proxied url, and using a proper basic auth header!

**Comment by epugh** [comment]
This has been fixed!
