### ISSUE TITLE
Prevent unrelated changes from impacting Docker cache

### ISSUE THREAD

**Issue by TheSench** [o19s/quepid#80]
**Is your feature request related to a problem? Please describe.**
I would like to be able to modify files like the Dockerfile or docker-compose.yml without breaking the caching on step 13 of the dockerfile (copying everything into the container).

**Describe the solution you'd like**
Either a `.dockerignore` file should be added that (at a minimum) excludes Dockerfiles and docker-compose.yml files, or the code that belongs inside the container should be moved to a subfolder, and only that code should be copied into it.

**Additional context**
I am trying to get the project building and running behind a pile of proxies.  This involves changing some environment variables and adding some steps to the Dockerfile.  Every time I make a change, I have to wait for `RUN bundle install` to run because **all** changes invalidate the cache on the `COPY . /srv/app` step.

**Comment by TheSench** [comment]
Bare-bones `.dockerignore` file:
```
Dockerfile.*
docker-compose*.yml
```
I'm sure there are more files in this project that are not needed in the container.

**Comment by o19s-admin** [comment]
Thanks for sharing this.   I want the dev experience to be easier.

**Comment by epugh** [comment]
Do you mind raising this as a PR @TheSench ?   That way I can track the change, and having something to review as a commumity?
