### ISSUE TITLE
Issues with larger query sets when populating books or creating snapshots

### ISSUE THREAD

**Issue by OkkeKlein** [o19s/quepid#800]
**Describe the bug**
Weird stuff was happening when creating snapshots or populating books

Solution:
add `client_max_body_size 100M;` to nginx.conf

**Comment by epugh** [comment]
Interesting...   are you saying that in yoru use case, the data going back and forth is so large that you need to increase the size in nginx?   To 100 MB?   I'd love to see a PR demonstrating where exactly you added this...

**Comment by OkkeKlein** [comment]
you can add it to your /location in nginx conf

**Comment by epugh** [comment]
can you check the attached PR?   I suspect anywhere where you have large documents, that this becomes an issue!  Nice fix!
