### ISSUE TITLE
"Copy" button for query

### ISSUE THREAD

**Issue by jeffryedvm** [o19s/quepid#811]
It's difficult to copy the query from the UI to paste elsewhere.  A "copy" button or icon next to the query would be very useful.

In the case shown, the "85" gets included on the right-mouse click select.
![Capture](https://github.com/o19s/quepid/assets/94408841/eec51c33-0a07-40d1-9371-1fe90b11a6db)

**Comment by epugh** [comment]
<img width="576" alt="image" src="https://github.com/o19s/quepid/assets/22395/5e32445c-484f-42f4-a295-989234bdae67">

Would this work?   I don't want to clutter up the main interface much...
