### ISSUE TITLE
Show new/unrated docs

### ISSUE THREAD

**Issue by jeffryedvm** [o19s/quepid#818]
I'd like to have the option to have only new, unrated docs (frogs) show when making judgements.

![Capture](https://github.com/o19s/quepid/assets/94408841/c9032926-6920-41a6-b8fb-732c6ab4668b)

**Comment by epugh** [comment]
@jeffryedvm I'm going to close this since the Books of Judgements approach is the preferred approach for managing the work of judging docs......   Please speak up though if that approach isn't working for you'all!
