### ISSUE TITLE
REDIS_URL does not override value in .env

### ISSUE THREAD

**Issue by fortinj66** [o19s/quepid#82]
**Describe the bug**

Quepid 6.1.0

Docker Images should not have .env files
REDIS_URL does not override value in .env

**To Reproduce**
run quepid in production mode with REDIS_URL defined on docker-compose.yml.prod
quepid will still use value in .env

**Expected behavior**
REDIS_URL would override .env

**Additional context**
I had to override the start process and remove the .env first before starting foreman...

**Comment by epugh** [comment]
Thanks for reporting this!   Out of curiosity, did the recent addition of this `.dockerignore` file maybe fix this issue?  https://github.com/o19s/quepid/blob/master/.dockerignore
The current released Docker images were built before the `.dockerignore` was added...

**Comment by epugh** [comment]
We think this is fixed in release 6.1.1, however haven't had a chance to confirm it fixed.

**Comment by worleydl** [comment]
This seems to be resolved in 6.1.1.
