### ISSUE TITLE
Unrating a document in the judging interface moves to the Book Judgments list page

### ISSUE THREAD

**Issue by david-fisher** [o19s/quepid#830]
**Describe the bug**
I rate a document, go back to previous, select unrate, and end up on the judgments list for the book, not on the next query doc pair to rate.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot 2023-09-14 at 2 10 00 PM](https://github.com/o19s/quepid/assets/1194968/431f1bb7-3312-4b87-8e06-54c2b180247b)
![Screenshot 2023-09-14 at 2 11 02 PM](https://github.com/o19s/quepid/assets/1194968/072f823a-f442-40b0-8d0a-03bf72309df5)

**Comment by epugh** [comment]
Apparently we need a https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_back_or_to
