### ISSUE TITLE
Enable evaluation of results generated offline

### ISSUE THREAD

**Issue by mkr** [o19s/quepid#839]
**Is your feature request related to a problem? Please describe.**
I'm using a search engine or information retrieval mechanism currently not supported by Quepid. I'm running a set of queries against this system and generate results "offline" (i.e. outside of Quepid). I would like to upload these results into Quepid in order to judge them and calculate some ranking metrics (NDCG/AP). 

**Describe the solution you'd like**
I imagine the possibility to upload CSVs/TSVs or similar in the Case Creation dialog/wizard. The results file would contain the following information:
* query - the query keywords
* doc id - the returned document id
* position - the position of the document in the returned results
* ... - any other field (e.g. `title`, `abstract` in the upload should be considered an additional field per document)
The solution should be able to handle CSV uploads of considerable size (e.g. 100 queries x 40 results x 300 bytes per row for query, doc id, position and further document info = 1.2MB)

**Describe alternatives you've considered**
Use another solution such as Google spreadsheets.

**Comment by epugh** [comment]
we should test the server side upload version and make sure it works there too...   Heroku will time you out if your request takes longer than 30 seconds...

**Comment by epugh** [comment]
So, to clarify this issue, we do have this capablity in the branch, but your testing with a larger file timed out, correct?   https://github.com/o19s/quepid/pull/788 is the branch with the current code...

**Comment by epugh** [comment]
This is now done!  At least, a basic MVP ;-).
