### ISSUE TITLE
Let an Admin post a message to users

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#848]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to communicate to users that things are going to happen, and no way to communicate it.

**Describe the solution you'd like**
Be able to put up a bit o' HTML that is show to the users.  Let them click close, and not see it again.  If a new message is posted, then they will get the new message.   If the message is "timed" well, you remove the message, and then it no longer shows up.   It doesn't "expire" by itself.

**Describe alternatives you've considered**
We have "sort" of used intercom on the hosted solution.

**Additional context**

**Comment by epugh** [comment]
Here is some potential HTML that could go in a messages box...

```
<div class="alert alert-info" role="alert">
  A simple info alert—check it out!
</div>
```

**Comment by flaxsearch** [comment]
Some examples of the sort of messages I'd like to be able to put up (excuse my HTML):

<div class="alert alert-info" role="alert">
  Want to learn how to use Quepid to tune relevance? Join OSC's <a href=https://opensourceconnections.com/training/>self-led training courses</a>
</div>

<div class="alert alert-info" role="alert">
We've just added <strong>brand new features</strong> to Quepid - check out Eric Pugh's <a href=https://opensourceconnections.com/blog/>blog</a> for more details
</div>

<div class="alert alert-info" role="alert">
The Call for Papers for <i>Haystack US 2023</i> is <a href=https://opensourceconnections.com/cfp>now open</a> - submit a talk on how you use Quepid!
</div>

**Comment by epugh** [comment]
This has been done for a while!
