### ISSUE TITLE
Needing an owner really cramps my style

### ISSUE THREAD

**Issue by david-fisher** [o19s/quepid#851]
Son, the owner thing is stupid...

Let's get rid of it.

Discuss

**Comment by epugh** [comment]
I wanted to confirm that when we talk about "owner", we are referring to our issues with Scorers right?

**Comment by david-fisher** [comment]
Scorers for certain. 

More generally, I appreciate the need for some notion of access protection, but once granted, eg via a shared case, *all* access should follow for any of the objects we diddle about. Endpoints come to mind. Having to clone one, instead of being able to edit, is an annoyance.

Perhaps Copy On Write semantics, to prevent someone from mauling objects.

**Comment by epugh** [comment]
Scorers is fixed in quepid version `7.13.0-dev8`, if you have access via either a team or being the owner, you can delete it/edit it/work with it.

**Comment by epugh** [comment]
Going to close this for now, since I think i sorted out what owner means in all the palces it touches, cases, books, scorers, search_endpoints, and it is just how we track something until it is shared with a team...!
