### ISSUE TITLE
Unable to clone a case without full history

### ISSUE THREAD

**Issue by janhoy** [o19s/quepid#86]
**Describe the bug**
I cannot clone a Case with only one try. If I clone with full try history it succeeds.

**To Reproduce**
1. Click 'clone' on a case
2. Select one of the tries and hit 'clone'
3. An error msg "Unable to clone you case. Please try again." shows up
4. Try again, but this time select 'Include the entire try history'
5. This time the clone succeeds

**Expected behavior**
Should be able to clone one try only (and ideally the dropdown should show the newest try on top)

**Additional context**
I have started Quepid about one week ago from docker-compose

**Comment by epugh** [comment]
Let us know @janhoy if you still see the issue.
