### ISSUE TITLE
Syncing Judgment Book on a Case Should Only Update Scores for Queries in Case

### ISSUE THREAD

**Issue by jvia** [o19s/quepid#871]
**Is your feature request related to a problem? Please describe.**
Currently, when you go to update the scores for the queries in a case using the judgement book, every query in the book is added to the case. This means you can't share a judgment book between different cases unless you want to share every query. Below is a diagram to capture what is happening.

Here I have two cases sharing a single judgment book:

```
├── Book
│   ├── Query1
│   ├── Query2
│   └── Query3
├── CaseA
│   └── Query1
└── CaseB
    ├── Query2
    └── Query3
```

After syncing CaseA with the book, all queries are added:

```
├── Book
│   ├── Query1
│   ├── Query2
│   └── Query3
├── CaseA
│   ├── Query1
│   ├── Query2
│   └── Query3
└── CaseB
    ├── Query2
    └── Query3
```

**Describe the solution you'd like**
I would like to update the scores for the queries in the case using the judgment book, that is all.

**Describe alternatives you've considered**
N/A

**Comment by epugh** [comment]
@david-fisher  can you weigh in here?   I can't quite remember what we discussed ;-)
