### ISSUE TITLE
Snapshot API ({server_url}/quepid/api/cases/{CASE_ID}/snapshots/{SNAPSHOT_ID}?shallow=true) to support CSV format too

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#880]
**Is your feature request related to a problem? Please describe.**
Usually snapshots are compared to generate comparison reports using pandas. Although pandas work with JSON format (existing format of this API) too but would appreciate if CSV format as for other snapshots apis to be supported by this api too.

**Describe the solution you'd like**
Introduce 'format' parameter (&format=csv) to this api that default to JSON and supports csv too.

**Describe alternatives you've considered**
Export JSON and transform it to generate CSV to get on with comparisons (for e.g. jaccard similarity)

**Comment by epugh** [comment]
This is what the current rating export looks like:
```
query,docid,rating
actions,l_6763,0.0
actions,l_3811,1.0
actions,l_1355,1.0
actions,l_4003,1.0
actions,l_1348,0.0
actions,l_4094,0.0
actions,l_1354,1.0
actions,l_6998,1.0
actions,l_28664,1.0
actions,l_4001,1.0
representing,l_30961,1.0
representing,l_30963,0.0
representing,l_24335,1.0
```

So, would this be good format for the snapshots?

**Comment by epugh** [comment]
@atarora  does this end point work for you?   
![image](https://github.com/o19s/quepid/assets/22395/4afb23d9-4b51-455b-9f61-27a18759f588)

Here is the url: http://localhost/api/export/ratings/5.csv?file_format=basic_snapshot&snapshot_id=1

and the output:
```
query,docid,rating
preservation,l_5652,0.0
preservation,l_6455,1.0
preservation,l_5653,1.0
preservation,l_6456,0.0
preservation,l_10486,0.0
preservation,l_19934,0.0
preservation,l_7701,1.0
preservation,l_16019,1.0
preservation,l_5648,1.0
preservation,l_1037,0.0
takes,l_31018,1.0
takes,l_26259,0.0
takes,l_5365,0.0
takes,l_5364,0.0
```

**Comment by epugh** [comment]
Going to call this one done then...
