### ISSUE TITLE
Quepid to support 'per query' qOptions to support dynamic query params

### ISSUE THREAD

**Issue by atarora** [o19s/quepid#881]
**Is your feature request related to a problem? Please describe.**
I have some dynamic query parameters in my search api that needs to be added to every query separately.

**Describe the solution you'd like**
There is a qOptions on the queries which could be leveraged for the same.

**Describe alternatives you've considered**
There are no alternatives to this approach unless i make a separate case for each query (which definitely sounds unreasonable and overkill!)

**Comment by epugh** [comment]
this will ship in 7.10!
