### ISSUE TITLE
thor command is not available on docker images > 7.9.2

### ISSUE THREAD

**Issue by vincetrumental** [o19s/quepid#888]
**Describe the bug**
thor command cannot be run from quepid app containers.

**To Reproduce**
1. deploy docker image tagged > 7.9.2 (for instance `latest` , 7.10.0 or 7.11RC*)
2. run `docker-compose run app thor list` or `docker run  o19s/quepid:7.11.0-rc5  thor list`
3. See error:
`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "thor": executable file not found in $PATH: unknown.`

**Expected behavior**
Must return the list of tasks that can be run with thor

**Additional context**
the fact that thor is not present in gem list seem dubious (it was on 7.9.2) . See `docker run  o19s/quepid:7.10.0 gem list`

**Comment by epugh** [comment]
thanks for spotting this....

**Comment by epugh** [comment]
Err, now fixed in #904

**Comment by norbertogomez** [comment]
Hey! while following the steps on the installation guide https://github.com/o19s/quepid/wiki/Installation-Guide, I am facing the same issue with the latest tag and previous one 7.12.3

Am I doing something wrong or this should be reopened?

![image](https://github.com/o19s/quepid/assets/4679449/1ac9935c-452e-472b-8eae-6994b3d2c564)
![image](https://github.com/o19s/quepid/assets/4679449/d523ce52-7b85-48dc-8a2b-246fb833350f)

**Comment by epugh** [comment]
Humm.....    Stupid Thor!   I clearly need some tests that exercise a release build...   for things like this...  Looking more...  Thanks @norbertogomez  for reporting.

**Comment by epugh** [comment]
Okay, it appears that to run thor you need `bundle exec thor list` style..  tried to eliminate the `bundle exec` with no luck.   

Please try `docker run o19s/quepid:7.13.1-beta2 bundle exec thor list` for example...
