### ISSUE TITLE
Custom headers not sent for searchapi

### ISSUE THREAD

**Issue by dacox** [o19s/quepid#890]
**Describe the bug**
When using `searchapi` as an endpoint, the custom headers are never sent.
Upon inspection of the request headers, this appears to be the case with and without using quepid as a proxy.

**To Reproduce**
1. Create a new Case
2. In the wizard, setup a new endpoint using searchapi
3. Add a custom header, say `{ "Authorization": "Token BLAHBLAHVLAH"}`
4. Click "Try" to test out the endpoint
5. Inspect the request headers - no custom header is sent (it is sent to elasticsearch type endpoints, for example)

**Expected behavior**
The custom headers would be sent/propagated regardless of endpoint type

**Screenshots**

**Additional context**
I am willing to submit a PR, but a general pointer in the right direction would be helpful - I have not used angular or rails frequently

CC @epugh as it seems like you worked on this area recently

**Comment by epugh** [comment]
this has been released to app.quepid.com and I am about to do a fresh docker image....

**Comment by epugh** [comment]
Going to close as Tiago has confirmed the fix on the #quepid channel....

**Comment by dacox** [comment]
> this has been released to app.quepid.com and I am about to do a fresh docker image....

Thanks @epugh - appreciate it!

**Comment by epugh** [comment]
I had actually been lax on updating the release notes...    Also, are you a member of Relevance Slack?  we have a #quepid channel there...

**Comment by dacox** [comment]
Ooh, I am not! I will join.
