### ISSUE TITLE
Migrate the NDCG@10 scorer from app.quepid.com to Docker version and Dev setup

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#91]
**Describe the bug**
We have created a NDCG@10 scorer that is the default scorer in app.quepid.com.   However, we haven't migrated that scorer to either the Docker version of Quepid OR the dev version.  This means if you run Quepid in either of those modes, then you must copy the NDCG@10 scorer from app.quepid.com to your setup.

**To Reproduce**
1. Look at your custom scorers, you will notice you don't have the NDCG@10 that is in app.quepid.com.

**Expected behavior**
We expect a set of different scorers to be available regardless of if you are running Quepid as a developer, or on prem via Docker image, or on app.quepid.com.  These should include P@, DCG@, CG@, MRR@ to start with.

**Additional context**
Right now we only have the old V1 scorer available to dev and docker, and our better newer scorers only in app.quepid.com.  There isn't a well defined "seed" apprach.

Maybe we should think about having our scorers that we ship in a db/scorers, and that an initializer checks and updates them in the database if the `scorer.js` is newer that what is in the database?

**Comment by epugh** [comment]
@janhoy we are getting close on this!

**Comment by janhoy** [comment]
I have seen "a few" commits lately, yes :) Thanks for improving the Docker version.

**Comment by epugh** [comment]
And we merged #100

**Comment by janhoy** [comment]
Will there be a new release of quepid and docker images on hub for this improvement? I just re-installed my env (with Mysql) and after an upgrade I suppose I could just do `db:migrate` to get to the new stuff?

**Comment by epugh** [comment]
Yes..    In place migration will be supported (joys of a hosted platform ;-) ).

My plan is to actually release 6.2 tomorrow (after the presentation Berlin Buzzwords)..    It has some pretty significant database migrations, so I need time to make sure that the hosted platform gets a good backup, we release carefully, and then test thoroughly.   If you want to try out the 6.2 version, I have published a prelease image:

https://hub.docker.com/layers/o19s/quepid/6.2-prerelease/images/sha256-306ef465d02feb0efaba62d0e7724c214f62ad68fdabec08e6fb840d30887a4b?context=explore

**Comment by janhoy** [comment]
I tested prerelease image, and ran `db:migrate` but unfortunately it crashed with this log

https://gist.github.com/5ff8003acb2b548bcacbb57409c4c74e

My MySql DB version is 5.7.26 while the one in docker-compose is 5.6.37, which could perhaps be the reason?

**Comment by janhoy** [comment]
I nuked the db `db:drop` and then ran `db:setup` from scratch with the new prerelease image, and there were no issues (with same DB 5.7.26). My previous DB was just a standard db from `quepid:latest`, with three added users, one team, one case and two queries with setings. So I guess it makes sense to test the migration on some existing DB, perhaps it crashes with 5.6 as well?
