### ISSUE TITLE
cases are saved during creation even when aborted

### ISSUE THREAD

**Issue by vincetrumental** [o19s/quepid#920]
**Describe the bug**
When I create a new case, and I cancel the creation, the case is saved anyway

**To Reproduce**
on version 7.13.0 (on-prem docker)
1. Click on "Relevancy Cases" -> "Create a case" or "+ Add new"
2. at some point before FINISH step, click on the top-right cross in the pop-in window
3. go to the cases lists, a new case appears named "Case _X_" or "Case: _X_" (the colon depends on which button you clicked to create the case)

**Expected behavior**
no case is created until you click "Finish"

**Comment by epugh** [comment]
Just pushed up a PR..  turned out this was easy to fix!
