### ISSUE TITLE
"General" case export produces csv with empty 'Information Need' and 'Notes' columns

### ISSUE THREAD

**Issue by peterdm** [o19s/quepid#923]
**Describe the bug**
When exporting a case using the "General" format, the final two columns "Information Need" and "Notes" are empty even when these fields are populated in the case.

**To Reproduce**
1. Create a new case
2. Add a query
3. Toggle Notes
4. Enter notes and information need then save.
5. Export (General)
6. See missing values in the last two columns

**Expected behavior**
Expecting the Information Need and Notes values to appear in the CSV.

**Screenshots**

**Additional context**

**Comment by epugh** [comment]
thanks!   Doing some housekeeping, so will add this to todays "snow day" list.

**Comment by epugh** [comment]
Added "Options" to the export in case you have defined any at the query level.

**Comment by epugh** [comment]
where are you doing the export from?   app.quepid.com or somewehre else?

**Comment by epugh** [comment]
fix is live in app.quepid.com...
