### ISSUE TITLE
Custom Search API setup error

### ISSUE THREAD

**Issue by erikhatcher** [o19s/quepid#950]
Quepid is not working with a custom search API

![image](https://github.com/o19s/quepid/assets/209189/907ae2d7-80d6-414b-96de-1aa504be3f7e)

I'm trying to get https://github.com/mongodb-developer/atlas-search-java-server to work with Quepid (Atlas Search via this search service)

**Comment by epugh** [comment]
seeing that we are loosing the default query that you put in after doing a ping wiht another custom search api.
