### ISSUE TITLE
Networking issues when using local Quepid installation and local search engine in Docker

### ISSUE THREAD

**Issue by wrigleyDan** [o19s/quepid#961]
**Describe the bug**
When setting up and using Quepid locally and trying to access a local search engine installation via the Custom Search API endpoint a status code 500 is returned.
The reason for this is that Quepid and the search engine are not within the same network when running in Docker. It is strange to not see this working and receive a "Connection refused" error.

**To Reproduce**
1. Have a search engine running in a Docker container, e.g. Elasticsearch running on localhost:9200 (assuming es-tmdb for this example)
2. Have Quepid running in a Docker container, e.g. on localhost:3000
3. Create a case with the following settings:
URL: http://localhost:9200/tmdb/_search
API Method: POST
Query:
```
{
  "query": {
    "match": {
      "title": "rambo"
    }
  }
}
```

**Expected behavior**
Would be nice to see this working although containers are in different networks.

**Screenshots**
![image](https://github.com/o19s/quepid/assets/54574577/1116dd3b-97a4-4d7f-8dd1-b8686e0666e5)

![image](https://github.com/o19s/quepid/assets/54574577/800b7f78-4924-4dbb-a932-3945eeb0afaf)

**Additional context**
n/a

**Comment by epugh** [comment]
Okay, so I didn't Solve the problem, but I do now trap the error and provide a nice 500 error in json!
