### ISSUE TITLE
Retire the "Communal Scorer" Idea?

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#98]
It turns out you can create a Scorer that is labeled as "Communal", which means it isn't a system default scorer OR a team scorer.   In production we have exactly 0 of these!

I did dig around, and found out that it is still supported, in the sense that you can pick a communal scorer:

![Screenshot at Mar 14 10-40-01](https://user-images.githubusercontent.com/22395/76684199-3422d880-65e0-11ea-9f6a-cb2e6ef91b88.png)

However, it seems like the useful of this feature isn't really there.  If you run your own Quepid, you would use the Default Scorer capablity.  Or, you use the Team capablity and share it with your team.   I *think* this is from the Dawn of the Quetaceous Era, when we didn't have Teams.

**Describe the solution you'd like**
I would like to remove this concept from Quepid.

**Describe alternatives you've considered**
We could document this feature, but again, not quite seeing the use case.

**Additional context**
We need @softwaredoug and maybe @ychaker or @omnifroodle to weigh in here.

**Comment by softwaredoug** [comment]
+1 to anything you can do to simplify scorers. I don't think I realize this existed.

**Comment by epugh** [comment]
Okay, I added a PR..  @worleydl can you review?
